GradleUp/shadow

- build.gradle
- src/main/groovy/com/github/jengelman/gradle/plugins/shadow/relocation/SimpleRelocator.groovy
- src/main/groovy/com/github/jengelman/gradle/plugins/shadow/transformers/ApacheNoticeResourceTransformer.groovy
- src/main/groovy/com/github/jengelman/gradle/plugins/shadow/transformers/AppendingTransformer.groovy
- src/main/groovy/com/github/jengelman/gradle/plugins/shadow/transformers/ComponentsXmlResourceTransformer.groovy
- src/main/groovy/com/github/jengelman/gradle/plugins/shadow/transformers/GroovyExtensionModuleTransformer.groovy
- src/main/groovy/com/github/jengelman/gradle/plugins/shadow/transformers/IncludeResourceTransformer.groovy
- src/main/groovy/com/github/jengelman/gradle/plugins/shadow/transformers/ManifestResourceTransformer.groovy
- src/main/groovy/com/github/jengelman/gradle/plugins/shadow/transformers/PropertiesFileTransformer.groovy
- src/main/groovy/com/github/jengelman/gradle/plugins/shadow/transformers/ServiceFileTransformer.groovy
- src/test/groovy/com/github/jengelman/gradle/plugins/shadow/transformers/ComponentsXmlResourceTransformerTest.groovy
- src/test/groovy/com/github/jengelman/gradle/plugins/shadow/util/JarBuilder.groovy
- src/test/groovy/com/github/jengelman/gradle/plugins/shadow/util/PluginSpecification.groovy
Wanted to upgrade my project to Gradle 2.5 today but noticed shadow was broken - because I wanted to continue the upgrade today I was looking into a fix for the problem. Basically Gradle 2.5 bundles only Maven 3 so the `plexus-utils` are no longer relocated in a different package.
This changes the imports to the new (original) packages and adds a dependency on the original `plexus-utils` which should (hopefully) maintain compatibility with older Gradle versions as well. While I have tested this successfully on Gradle 2.5, as well as some older Gradle versions like 2.4 and 1.12 I'm not completely sure if this will always work for older Gradle versions.
The fix is probably not perfect, so if you've started already or see a better way feel free to close this, just thought it may help you to …
> Fix compatibility with Gradle 2.5. Fixes #147

- src/main/groovy/com/github/jengelman/gradle/plugins/shadow/transformers/ServiceFileTransformer.groovy
- src/test/groovy/com/github/jengelman/gradle/plugins/shadow/TransformerSpec.groovy
The relocation rules should be taken into account while merging service files. This involves both the name and the content of the service files.
> Perform relocation while merging service files

- src/main/groovy/com/github/jengelman/gradle/plugins/shadow/ShadowJavaPlugin.groovy
- src/test/groovy/com/github/jengelman/gradle/plugins/shadow/ShadowPluginSpec.groovy
Fixes #275
Also properly ignore a long test of large ZIPs
> Use dependency configurations introduced in Gradle 3.3 if possible

- src/docs/asciidoc/90-changes.adoc
- src/main/groovy/com/github/jengelman/gradle/plugins/shadow/transformers/PropertiesFileTransformer.groovy
- src/test/groovy/com/github/jengelman/gradle/plugins/shadow/transformers/PropertiesFileTransformerSpec.groovy
The new keyTransformer property can be used to transform keys in properties files, e.g. because they contain class names about to be relocated. Its value can be set to a closure that receives the original key and returns the key name to be used in the resulting properties file.
We need this for junit-console-launcher because it uses joptsimple by @pholser which we want to relocate to a different package in order to enable users to test code that uses a different version of joptsimple. However, the joptsimple JAR contains properties files that contain keys that are class names.
> Introduce keyTransformer property for PropertiesFileTransformer

- src/docs/asciidoc/10-configuring.adoc
> Fix typo in docs.

- src/main/groovy/com/github/jengelman/gradle/plugins/shadow/ShadowPlugin.groovy
The build scan plugin will only ever be applied to the root project. The current integration with the plugin assumes the project with the build scan plugin applied and the project with the shadow plugin applied are the same project. This will only ever be the case in a single-project build. In the case of a multi-project build these diverge.
Change the existing logic to look for the build-scan plugin on the root project, as well as include the complete task path in custom value keys as there exists the possibility that multiple `shadowJar` tasks exist within a single multi-project.
> Make build scan integration work with multi-project builds

- gradle/dependencies.gradle
ASM 6.0 is officially released out of beta. This fixes issue 294.
> Update ASM to 6.0.

- src/main/groovy/com/github/jengelman/gradle/plugins/shadow/ShadowApplicationPlugin.groovy
Remove warning when using the shadow plugin:
`Using TaskInputs.file() with something that doesn't resolve to a File object has been deprecated and is scheduled to be removed in Gradle 5.0. Use TaskInputs.files() instead`
> update inputs.file to inputs.files, to remove warning

- gradle/dependencies.gradle
ASM 6.2 brings support for JDK11, http://asm.ow2.io/versions.html. 
Without this builds are failing with:
```
Caused by: java.lang.IllegalArgumentException: Unsupported class file major version 55
at shadow.org.objectweb.asm.ClassReader.<init>(ClassReader.java:166)
at shadow.org.objectweb.asm.ClassReader.<init>(ClassReader.java:148)
at shadow.org.objectweb.asm.ClassReader.<init>(ClassReader.java:136)
at shadow.org.objectweb.asm.ClassReader.<init>(ClassReader.java:237)
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:4 …
```
> Upgrade ASM to 6.2 (JDK 11 support)

- gradle/dependencies.gradle
- src/main/groovy/com/github/jengelman/gradle/plugins/shadow/transformers/Log4j2PluginsCacheFileTransformer.groovy
- src/test/groovy/com/github/jengelman/gradle/plugins/shadow/transformers/Log4j2PluginsCacheFileTransformerTest.groovy
I originally wrote this in its own plugin which attached itself to the shadow plugin. It's better to bundle the transformer into the shadow plugin inself instead of my own orthoginal plugin.
https://issues.apache.org/jira/browse/LOG4J2-673
https://github.com/paul-nelson-baker/gradle-shaded-log4j2-cachefile-transformer/blob/master/src/main/java/io/paulbaker/gradle/shadow/transform/Log4j2PluginsCacheFileTransformer.java
https://github.com/edwgiz/maven-shaded-log4j-transformer/blob/master/src/main/java/com/github/edwgiz/mavenShadePlugin/log4j2CacheTransformer/PluginsCacheFileTransformer.java
> Migrating Maven transformer to Gradle.

- src/main/groovy/com/github/jengelman/gradle/plugins/shadow/tasks/ShadowCopyAction.groovy
- src/main/groovy/com/github/jengelman/gradle/plugins/shadow/tasks/ShadowJar.java
- src/test/groovy/com/github/jengelman/gradle/plugins/shadow/ShadowPluginSpec.groovy
With this PR, the [officially recommended Gradle config for reproducible builds](https://docs.gradle.org/4.8/userguide/working_with_files.html#sec:reproducible_archives) now successfully creates reproducible builds when used with shadowJar:
```
tasks.withType(AbstractArchiveTask) {
preserveFileTimestamps = false
reproducibleFileOrder = true
}
```
Gradle 3.4 added support for reproducible builds of archives, but shadowJar doesn't respect the preserveFileTimestamps setting despite extending AbstractArchiveTask which exposes that. This PR makes the shadowJar task handle the preserveFileTimestamps setting. (I believe the reproducibleFileOrder setting is handled by Gradle in a way that already works for shadowJar.)
Solves https://github.com/johnrengelman/shadow/issues/229 and …
> Support AbstractArchiveTask.preserveFileTimestamps for reproducible builds

- gradle/dependencies.gradle
- src/docs/asciidoc/10-configuring.adoc
- src/docs/asciidoc/15-minimizing.adoc
- src/main/groovy/com/github/jengelman/gradle/plugins/shadow/internal/UnusedTracker.groovy
- src/main/groovy/com/github/jengelman/gradle/plugins/shadow/tasks/ShadowCopyAction.groovy
- src/main/groovy/com/github/jengelman/gradle/plugins/shadow/tasks/ShadowJar.java
- src/main/groovy/com/github/jengelman/gradle/plugins/shadow/tasks/ShadowSpec.java
- src/test/groovy/com/github/jengelman/gradle/plugins/shadow/ShadowPluginSpec.groovy
(this is a follow up of https://github.com/johnrengelman/shadow/pull/273)
This commit adds two new configuration options to the 'shadowJar' task.
When 'minimize' is set the shadow JAR would only include the classes
for the project the task operates on and its dependencies. The user can
protect other classes from minimization by excluding their module.
Here's an example configuration
shadowJar {
minimize {
exclude(dependency('junit:junit:.*'))
}
}
> Implemented JAR minimization

- gradle/dependencies.gradle
Just a dependencies upgrade that resolves the `java.lang.UnsupportedOperationException: This feature requires ASM7` error when using JDK 11.
As a side note, upgrades to `org.ow2.asm` would almost always require an upgrade
of the `jdependency` lib, where the newest ASM opt codes are supported.
--------
Resolves #406
> Upgrade ASM to 7.0-beta and jdependency to 2.1.1

- src/main/groovy/com/github/jengelman/gradle/plugins/shadow/tasks/ShadowCopyAction.groovy
> [Fixes #408] always close input streams we create

- src/main/groovy/com/github/jengelman/gradle/plugins/shadow/tasks/ShadowCopyAction.groovy
- src/main/groovy/com/github/jengelman/gradle/plugins/shadow/transformers/ServiceFileTransformer.groovy
This pull request fixes some memory leak issues we noticed when using the Shadow plugin with long lived Gradle daemons. The commit addresses two items:
1. `RelativeArchivePath` was unnecessarily keeping a reference to `DefaultFileCopyDetails` which is a pretty heavyweight object. Turns out this is never actually used so this has been removed.
2. The whole reason item (1) was an issue was is because results of calls to pattern specs are actually [cached](https://github.com/gradle/gradle/blob/master/subprojects/core-api/src/main/java/org/gradle/api/tasks/util/internal/CachingPatternSpecFactory.java#L63) by Gradle, such as [this one](https://github.com/johnrengelman/shadow/blob/master/src/main/groovy/com/github/jengelman/gradle/plugins/shadow/tasks/ShadowCopyAction.groovy#L260). The cache …
> Avoid leaking plugin classes into Gradle's pattern spec result cache

- src/docs/getting-started/README.md
Fix sub-list indent for `uploadShadow` documentation.
> Getting Started docs formatting fix

- src/main/groovy/com/github/jengelman/gradle/plugins/shadow/tasks/ShadowJar.java
As I tested the plugin with gradle 5.2 I got an error. Gradle was unable to create the shadowJar task because of duplicate metaClass methods. Not sure if we really have to remove it here or it's more a problem of gradle.
> Remove ShadowJar MetaClass implementation. Fix for gradle 5.2

- src/main/groovy/com/github/jengelman/gradle/plugins/shadow/ShadowApplicationPlugin.groovy
This patch fixes a problem when `application`, `shadow` and
`com.palantir.docker` plugins are activated at the same time.
Exception:
```
An exception occurred applying plugin request [id: 'application']
> Failed to apply plugin [class
'com.github.jengelman.gradle.plugins.shadow.ShadowApplicationPlugin']
> No such property: provider for class:
org.gradle.api.internal.artifacts.publish.ArchivePublishArtifact
```
> Fix for com.palantir.docker interoperability.

- src/main/groovy/com/github/jengelman/gradle/plugins/shadow/tasks/ShadowJar.java
> Avoid UnusedTracker creation when minimizeJar is not requested

- build.gradle
- src/main/groovy/com/github/jengelman/gradle/plugins/shadow/transformers/ManifestAppenderTransformer.groovy
- src/test/groovy/com/github/jengelman/gradle/plugins/shadow/transformers/ManifestAppenderTransformerTest.groovy
Java's manifest attributes are implemented using a `HashMap`, which makes them useless when the attributes must be written in a particular order. E.g. for sealing packages in jars:
```
Name: com/example/
Sealed: true
```
Implement a `Transformer` which can append tags to a manifest while preserving their order.
~Note: This is a WIP - my transformer's current UI is based on Groovy's `Tuple2`. However, I'm sure that Groovy can support something better.~
The transformer's current API is:
```groovy
shadowJar {
transform(ManifestAppenderTransformer) {
append('Name', 'first/sealed/package/')
append('Sealed', true)
append('Name', 'second/sealed/package/')
append('Sealed', true)
}
}
```
> Add ManifestAppenderTransformer to support sealing packages in jars.

- src/main/resources/com/github/jengelman/gradle/plugins/shadow/internal/unixStartScript.txt
Fixes issue #465
For reference, gradle produces the following, which shadow should match:
```
for i do printf %s\\n "$i" | sed "s/'/'\\\\''/g;1s/^/'/;\$s/\$/' \\\\/" ; done
```
> Additional escapes for args processing

- src/docs/configuration/relocation/README.md
- src/docs/plugins/README.md
- src/main/groovy/com/github/jengelman/gradle/plugins/shadow/ShadowPlugin.groovy
The Java Gradle Plugin Development plugin, `java-gradle-plugin`,
automatically adds the full Gradle API to the `compile` configuration;
thus overriding a possible assignment of `gradleApi()` to the `shadow`
configuration.  Since it is never a good idea to include the Gradle API
when creating a Gradle plugin, the dependency is removed so that it is
not included in the resultant shadow jar.
> Add automatic handling of Gradle API when using java-gradle-plugin

- src/main/groovy/com/github/jengelman/gradle/plugins/shadow/internal/UnusedTracker.groovy
- src/test/groovy/com/github/jengelman/gradle/plugins/shadow/ShadowPluginSpec.groovy
If an API project dependency has a version number, then the check for the dependency name was wrong (i.e., it won't end with *myproject.jar* but say *myproject-1.0.jar*). I tried to create a change which is reasonably compatible with the previous behaviour in other cases.
> Fixed NPE when api project dependency has a version number.

- src/docs/configuration/README.md
Fixes https://github.com/johnrengelman/shadow/issues/508.
> Use empty string to disable version

- src/main/groovy/com/github/jengelman/gradle/plugins/shadow/ShadowJavaPlugin.groovy
> Use convention mapping for classifier on old gradle

- build.gradle
- gradle/dependencies.gradle
- gradle/wrapper/gradle-wrapper.properties
- src/main/groovy/com/github/jengelman/gradle/plugins/shadow/tasks/ShadowJar.java
- src/test/groovy/com/github/jengelman/gradle/plugins/shadow/ShadowPluginSpec.groovy
Gradle 6 introduces:
* warnings around the usage of `compile` and `testCompile` configurations as they will be removed in 7.0
* Gradle [Fails on duplicates by default](https://github.com/gradle/gradle/pull/10143/files) starting on 6.x. Before the default `DuplicateStrategy` was `INHERIT` which is to inherit the strategy from the parent copy spec, if any,  or `DuplicatesStrategy.INCLUDE` if the copy spec has no parent.
Also upgraded the build-info-extractor plugin as current version is not Gradle 6.x compatible with the following error:
```
> org.gradle.api.publish.maven.internal.publication.MavenPublicationInternal.getPublishableFiles()Lorg/gradle/api/file/FileCollection;
```
> Gradle 6.x support

- gradle/wrapper/gradle-wrapper.properties
- src/main/groovy/com/github/jengelman/gradle/plugins/shadow/internal/UnusedTracker.groovy
- src/main/groovy/com/github/jengelman/gradle/plugins/shadow/relocation/CacheableRelocator.groovy
- src/main/groovy/com/github/jengelman/gradle/plugins/shadow/relocation/SimpleRelocator.groovy
- src/main/groovy/com/github/jengelman/gradle/plugins/shadow/tasks/ShadowJar.java
- src/main/groovy/com/github/jengelman/gradle/plugins/shadow/transformers/AppendingTransformer.groovy
- src/main/groovy/com/github/jengelman/gradle/plugins/shadow/transformers/CacheableTransformer.groovy
- src/main/groovy/com/github/jengelman/gradle/plugins/shadow/transformers/GroovyExtensionModuleTransformer.groovy
- src/main/groovy/com/github/jengelman/gradle/plugins/shadow/transformers/ServiceFileTransformer.groovy
- src/main/groovy/com/github/jengelman/gradle/plugins/shadow/transformers/XmlAppendingTransformer.groovy
- src/test/groovy/com/github/jengelman/gradle/plugins/shadow/caching/AbstractCachingSpec.groovy
- src/test/groovy/com/github/jengelman/gradle/plugins/shadow/caching/MinimizationCachingSpec.groovy
- src/test/groovy/com/github/jengelman/gradle/plugins/shadow/caching/RelocationCachingSpec.groovy
- src/test/groovy/com/github/jengelman/gradle/plugins/shadow/caching/ShadowJarCachingSpec.groovy
- src/test/groovy/com/github/jengelman/gradle/plugins/shadow/caching/TransformCachingSpec.groovy
These changes make the `shadowJar` task compatible with the build cache.  
The task will still be cacheable if any of the following transformers are used:
- AppendingTransformer
- XmlAppendingTransformer
- ServiceFileTransformer
- GrroovyExtensionModuleTransformer
But the other out-of-the-box transformers are not cacheable yet (if they are added, the task will be marked as un-cacheable) but I can add caching for those with a future PR.  User-defined transformers will also make the task un-cacheable unless they declare the inputs of the transformer and annotate it with `@CacheableTransformer`.
Similarly, `SimpleRelocator` has been marked as cacheable, but any custom relocators will disable caching unless the class is annotated with `@CacheableRelocator`.
We've seen fairly significant task …
> Make shadowJar task cacheable

- src/main/groovy/com/github/jengelman/gradle/plugins/shadow/tasks/ShadowCopyAction.groovy
> #525: Remap MRJar classes correctly

- gradle/dependencies.gradle
Any attempt to run Gradle build with Shadow **5.2.0** on JDK 13+ fails with `Unsupported class file` exception, e.g.:
```
java.lang.IllegalArgumentException: Unsupported class file major version 57
at shadow.org.objectweb.asm.ClassReader.<init>(ClassReader.java:184)
at shadow.org.objectweb.asm.ClassReader.<init>(ClassReader.java:166)
at shadow.org.objectweb.asm.ClassReader.<init>(ClassReader.java:152)
at shadow.org.objectweb.asm.ClassReader.<init>(ClassReader.java:273)
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java: …
```
> Upgrade to ASM 7.2 to support JDK 14

- src/main/groovy/com/github/jengelman/gradle/plugins/shadow/relocation/SimpleRelocator.groovy
- src/test/groovy/com/github/jengelman/gradle/plugins/shadow/relocation/SimpleRelocatorTest.groovy
Fixes this use case on Windows:
```
relocate('io.opentelemetry', 'io.opentelemetry.auto.shaded.io.opentelemetry') {
exclude 'io.opentelemetry.auto.**'
}
```
The fix is to explicitly pass separator (`/`) to `SelectorUtils.matchPath`. The default when it's not passed is `File.separator`, so this change should have no effect on non-Windows OS.
> Fix excludes ant pattern on Windows

- src/main/groovy/com/github/jengelman/gradle/plugins/shadow/impl/RelocatorRemapper.groovy
- src/main/groovy/com/github/jengelman/gradle/plugins/shadow/relocation/Relocator.groovy
- src/main/groovy/com/github/jengelman/gradle/plugins/shadow/relocation/SimpleRelocator.groovy
- src/main/groovy/com/github/jengelman/gradle/plugins/shadow/transformers/Log4j2PluginsCacheFileTransformer.groovy
- src/main/groovy/com/github/jengelman/gradle/plugins/shadow/transformers/ServiceFileTransformer.groovy
- src/test/groovy/com/github/jengelman/gradle/plugins/shadow/relocation/SimpleRelocatorTest.groovy
Performance boost on large project (5:48 -> 2:02 min total duration).
- Changed signature of methods to accept `String` as path instead of `RelocatePathContext`/`RelocateClassContext` to prevent unnecessary allocations for builder objects
- Added extra string length checks to avoid string operations where possible
- Reordered checks in `canRelocateClass` so that expensive string replacement is the last operation
- (Main Optimization) Avoided string concatenation (which led to creating `StringBuilder` instances and expensive array copy operations) by adding check for first character being `/`: if so - perform a `startsWith` check with an offset.
> Optimizations to relocation checks. Up to 3x faster

- src/main/groovy/com/github/jengelman/gradle/plugins/shadow/ShadowExtension.groovy
- src/test/groovy/com/github/jengelman/gradle/plugins/shadow/PublishingSpec.groovy
When  dependencies in the `shadow` configuration are project dependencies, expose them in the `.pom` in the same way as dependencies on external modules.
Use case: a multi-project build that publishes API and implementation in separate jars, where the implementation is a shadow jar and needs a dependency on the API.
Fix for #541.
> Support project dependencies in the shadow configuration

- gradle/dependencies.gradle
@johnrengelman Any estimate on when the next version of the Shadow plugin will be released?
> Upgrade to ASM 7.3.1 to support JDK 15

- src/main/groovy/com/github/jengelman/gradle/plugins/shadow/transformers/ServiceFileTransformer.groovy
Fixes #530 
I ran a test between HEAD and this:
- HEAD (43a8d4e8ea5d07a29d1d012c16fd4e34f646f87c):
```
% ./gradlew --warning-mode=all shadowJar
Starting a Gradle Daemon (subsequent builds will be faster)
> Task :shadowJar
Property 'transformers.$0.serviceEntries' is not annotated with an input or output annotation. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0. See https://docs.gradle.org/6.3/userguide/more_about_tasks.html#sec:up_to_date_checks for more details.
BUILD SUCCESSFUL in 30s
2 actionable tasks: 2 executed
```
- this change:
```
% ./gradlew --warning-mode=all shadowJar
BUILD SUCCESSFUL in 6s
2 actionable tasks: 1 executed, 1 up-to-date
```
I also verified that the contents of the `META-INF/services` files were the same. I also ran an …
> Eliminate serviceEntries deprecation warning by making it private

- src/main/groovy/com/github/jengelman/gradle/plugins/shadow/ShadowApplicationPlugin.groovy
- src/main/groovy/com/github/jengelman/gradle/plugins/shadow/internal/JavaJarExec.groovy
This resolves the compatibility issue with Gradle 6.4+ caused
by changing task configuration at execution.
Fixes #574
> Update runShadow configuration

- src/docs/getting-started/README.md
This seems to be outdated since https://github.com/johnrengelman/shadow/pull/284.
> Fix outdated reference to runtime configuration

- src/docs/configuration/README.md
I was lost for a while, because the documentation wasn't showing the correct usage based on the latest versions of both Gradle (`6.5.1`) and Shadow (`6.0.0`).
Includes configuring using:
archiveBaseName.set()
archiveClassifier.set()
archiveVersion.set()
> Update README to reflect Gradle archive updates.

- gradle/dependencies.gradle
> Fix CVE-2020-9488 by bumping log4j -> 2.13.3

- gradle/wrapper/gradle-wrapper.properties
- src/main/groovy/com/github/jengelman/gradle/plugins/shadow/ShadowApplicationPlugin.groovy
- src/main/groovy/com/github/jengelman/gradle/plugins/shadow/ShadowJavaPlugin.groovy
- src/main/groovy/com/github/jengelman/gradle/plugins/shadow/internal/UnusedTracker.groovy
- src/main/groovy/com/github/jengelman/gradle/plugins/shadow/tasks/ShadowJar.java
- src/test/groovy/com/github/jengelman/gradle/plugins/shadow/ConfigurationCacheSpec.groovy
We (myself and @britter) believe this PR allows the Shadow Plugin to be used
in a Gradle 6.6+ build with --configuration-cache enabled.
We unfortunately did not get round to fixing the case where `minimize()` is
used, so it does not work if that is called in the build.
We're basically looking for suggestions on what we can do to improve it,
or whether it is good enough to go in as-is
Cheers
Tim (and Benedikt)
> Fixes to allow Configuration Caching in Gradle 6.6+

- src/main/groovy/com/github/jengelman/gradle/plugins/shadow/ShadowApplicationPlugin.groovy
- src/main/groovy/com/github/jengelman/gradle/plugins/shadow/ShadowJavaPlugin.groovy
Gradle 7 removes the `maven` plugin so even if you compile with an older
version and have the types available, it's possible that they are missing
at runtime.
To workaround this, this commit uses `pluginManager.withPlugin('maven')`
instead which doesn't need any type available on classpath.
> Make sure the plugin can be used with Gradle 7

- src/main/groovy/com/github/jengelman/gradle/plugins/shadow/ShadowJavaPlugin.groovy
- src/test/groovy/com/github/jengelman/gradle/plugins/shadow/PublishingSpec.groovy
Exclude api and implementation configurations from POM dependencies when publishing with the legacy maven plugin.
> Exclude api and implementation configurations from pom dependencies

- src/main/groovy/com/github/jengelman/gradle/plugins/shadow/tasks/ShadowCopyAction.groovy
This fixes an issue @CarterWilliam found where the Gradle daemon locks class files.
[log.txt](https://github.com/johnrengelman/shadow/files/6044833/log.txt)
> Close FileInputStream when remapping class

- src/main/groovy/com/github/jengelman/gradle/plugins/shadow/transformers/ServiceFileTransformer.groovy
The use of the abstract fields in the ServiceFileTransformer without super results in an error in newer Groovy versions since [PR 1050](https://github.com/apache/groovy/pull/1050). For the current Gradle 7.0 RC, that looks like this:
```
Caused by: groovy.lang.MissingPropertyException: No such property: count for class: com.github.jengelman.gradle.plugins.shadow.transformers.ServiceFileTransformer
at com.github.jengelman.gradle.plugins.shadow.transformers.ServiceFileTransformer$ServiceStream.append(ServiceFileTransformer.groovy:110)
at ...
```
Apart from that, the plugin is usable with Gradle 7.0, as far as I can tell.
> Use protected superclass fields via super because of GROOVY-9292

- src/main/groovy/com/github/jengelman/gradle/plugins/shadow/transformers/ApacheNoticeResourceTransformer.groovy
- src/main/groovy/com/github/jengelman/gradle/plugins/shadow/transformers/AppendingTransformer.groovy
- src/main/groovy/com/github/jengelman/gradle/plugins/shadow/transformers/ComponentsXmlResourceTransformer.groovy
- src/main/groovy/com/github/jengelman/gradle/plugins/shadow/transformers/DontIncludeResourceTransformer.groovy
- src/main/groovy/com/github/jengelman/gradle/plugins/shadow/transformers/GroovyExtensionModuleTransformer.groovy
- src/main/groovy/com/github/jengelman/gradle/plugins/shadow/transformers/IncludeResourceTransformer.groovy
- src/main/groovy/com/github/jengelman/gradle/plugins/shadow/transformers/ManifestAppenderTransformer.groovy
- src/main/groovy/com/github/jengelman/gradle/plugins/shadow/transformers/ManifestResourceTransformer.groovy
- src/main/groovy/com/github/jengelman/gradle/plugins/shadow/transformers/PropertiesFileTransformer.groovy
- src/main/groovy/com/github/jengelman/gradle/plugins/shadow/transformers/Transformer.groovy
- src/main/groovy/com/github/jengelman/gradle/plugins/shadow/transformers/XmlAppendingTransformer.groovy
- src/test/groovy/com/github/jengelman/gradle/plugins/shadow/TransformerSpec.groovy
This PR annotates transformers' configuration fields as inputs to solve the deprecation warnings.
Closes #601 
Fixes the remaining warnings in #530 (only the first one was addressed in #569)
Caveats:
* I've marked `PropertiesFileTransformer.keyTransformer` as internal, while I believe it should also be an input. Just annotating it with `@Input` will cause Gradle to eagerly calculate its value (passing `null` as parameter) which is not desirable. The solution may be wrapping the closure with `Property<>`, but I'm not totally sure. At least one other plugin in a similar situation seem to have gone with internal as well (https://github.com/ben-manes/gradle-versions-plugin/blob/master/src/main/groovy/com/github/benmanes/gradle/versions/updates/DependencyUpdatesTask.groovy#L76)
* Had to …
> Fix transformers deprecation warnings

- build.gradle
- buildSrc/build.gradle
- src/main/groovy/com/github/jengelman/gradle/plugins/shadow/ShadowJavaPlugin.groovy
The 'maven' plugin which is deprecated for quite some time is finally [removed](https://github.com/gradle/gradle/commit/53d7c1bcf272ff9bf1fc8e2145b458cb9072d06b) in Gradle 7.0. This also [affects](https://github.com/gradle/gradle/commit/eafc8d71fc2cf1bcfe565432d686cc25c06aedb9) the related classes (their replacements already live under org.gradle.api.publish.maven).
The ShadowJavaPlugin class currently imports them which makes it incompatible with Gradle 7 at compile time. By removing the imports and using Groovy's def variable declaration, the search for those old classes is deferred to runtime, only being called when the 'maven' plugin is applied and the classes are there as expected. So this change is compatible with use of the plugin in older Gradle versions.
As Gradle emits warnings …
> Remove imports of old maven plugin classes for Gradle 7.0 build compat

- gradle/dependencies.gradle
Currently running Gradle build which uses JavaToolchanin configured with JDK 18 results in this exception from the Shadow plugin:
```
Caused by: java.lang.IllegalArgumentException: Unsupported class file major version 62
at shadow.org.objectweb.asm.ClassReader.<init>(ClassReader.java:196)
at shadow.org.objectweb.asm.ClassReader.<init>(ClassReader.java:177)
at shadow.org.objectweb.asm.ClassReader.<init>(ClassReader.java:163)
at shadow.org.objectweb.asm.ClassReader.<init>(ClassReader.java:284)
at com.github.jengelman.gradle.plugins.shadow.tasks.ShadowCopyAction$StreamAction.remapClass(ShadowCopyAction.groovy:342)
at com.github.jengelman.gradle.plugins.shadow.tasks.ShadowCopyAction$StreamAction.remapClass(ShadowCopyAction.groovy:328)
at …
```
> Upgrade to ASM 9.2 for JDK 18 support.

- src/main/groovy/com/github/jengelman/gradle/plugins/shadow/ShadowApplicationPlugin.groovy
JavaExec.main has been deprecated in Gradle 7.1 and will be removed in
Gradle 8.0. Instead, JavaExec.mainClass property should be used.
> Fix Gradle 7.1 JavaExec.main property deprecation

- build.gradle
- gradle/dependencies.gradle
- src/test/groovy/com/github/jengelman/gradle/plugins/shadow/ApplicationSpec.groovy
- src/test/groovy/com/github/jengelman/gradle/plugins/shadow/PublishingSpec.groovy
- src/test/groovy/com/github/jengelman/gradle/plugins/shadow/RelocationSpec.groovy
- src/test/groovy/com/github/jengelman/gradle/plugins/shadow/ShadowPluginSpec.groovy
- src/test/groovy/com/github/jengelman/gradle/plugins/shadow/caching/RelocationCachingSpec.groovy
- src/test/groovy/com/github/jengelman/gradle/plugins/shadow/caching/ShadowJarCachingSpec.groovy
- src/test/groovy/com/github/jengelman/gradle/plugins/shadow/util/PluginSpecification.groovy
- src/test/groovy/com/github/jengelman/gradle/plugins/shadow/util/file/TestFile.java
Spock tests haven't been running since the migration to Spock 2. This PR fixes that.
> Make Spock tests run again

- src/main/groovy/com/github/jengelman/gradle/plugins/shadow/ShadowJavaPlugin.groovy
- src/main/groovy/com/github/jengelman/gradle/plugins/shadow/ShadowPlugin.groovy
Solves #674 
I've eliminated the `Project#afterEvaluate` call and added a bit to filter out the `gradleApi()` dependency to the dependency filter for the default task. The call to `Project#afterEvaluate` was conflicting with another plugin making a similar call, so removal is the recommended strategy. [See also](https://discuss.gradle.org/t/is-project-afterevaluate-the-proper-way-for-gradle-plugin-to-dynamically-create-default-tasks/31349).
> Moved graldeApi() exclusion to the task configuration.

- gradle/dependencies.gradle
Oops, it seems my PR (#672) to fix the Spock tests ended up breaking the JUnit tests. These two dependencies are needed when using `useJUnitPlatform()`.
> Make JUnit tests run again

- src/docs/configuration/README.md
- src/docs/getting-started/README.md
- src/docs/publishing/README.md
- src/main/groovy/com/github/jengelman/gradle/plugins/shadow/ShadowApplicationPlugin.groovy
- src/main/groovy/com/github/jengelman/gradle/plugins/shadow/ShadowJavaPlugin.groovy
Maven plugin (and upload task) has been completely removed from Gradle 7, which is now the minimum required version by Shadow. This PR removes the remnants of it.
> Remove maven plugin

- gradle/dependencies.gradle
- src/test/groovy/com/github/jengelman/gradle/plugins/shadow/TransformerSpec.groovy
In #647, I had to leave the test for `ManifestResourceTransformer` commented out, because that transformer has been broken since `JarOutputStream` was replaced by `ZipOutputStream` in Shadow 0.9.0/1.0.0. That was due to an issue upstream in Ant (https://github.com/apache/ant/pull/145) which has been fixed since version 1.10.10.
> Fix ManifestResourceTransformer

- src/main/groovy/com/github/jengelman/gradle/plugins/shadow/ShadowApplicationPlugin.groovy
- src/main/groovy/com/github/jengelman/gradle/plugins/shadow/ShadowBasePlugin.groovy
- src/main/groovy/com/github/jengelman/gradle/plugins/shadow/ShadowJavaPlugin.groovy
- src/main/groovy/com/github/jengelman/gradle/plugins/shadow/tasks/KnowsTask.groovy
- src/main/groovy/com/github/jengelman/gradle/plugins/shadow/transformers/ComponentsXmlResourceTransformer.groovy
- src/main/groovy/com/github/jengelman/gradle/plugins/shadow/transformers/XmlAppendingTransformer.groovy
- src/test/groovy/com/github/jengelman/gradle/plugins/shadow/transformers/ManifestAppenderTransformerTest.groovy
- src/test/groovy/com/github/jengelman/gradle/plugins/shadow/util/PluginSpecification.groovy
Omitting the visibility modifier creates a Groovy _property_ [1], which
is composed by:
* a _private_ backing field
* a public getter
* (+ setter if the property is not `final`)
It is unlikely to be an intended design as it makes access to those
fields awkward from statically typed languages
`ShadowBasePlugin.getCONFIGURATION_NAME()`.
This commit replaces such _properties_ with _public fields_ only.
This is a backward incompatible change as this removes public getters.
Here is what the generated class looked liked before this
commit (7.0.0):
```
$ javap -p -c -constants ShadowBasePlugin.class
Compiled from "ShadowBasePlugin.groovy"
public class com.github.jengelman.gradle.plugins.shadow.ShadowBasePlugin implements org.gradle.api.Plugin<org.gradle.api.Project>, groovy.lang.GroovyObject { …
```
> refactor: directly expose `static final String` fields / remove getters

- src/docs/getting-started/README.md
Fixes the instructions for adding the Gradle plugin to the buildscript classpath in the user guide.
Based on the instructions in the Gradle plugin portal:
https://plugins.gradle.org/plugin/com.github.johnrengelman.shadow
Fixes #750.
> Fix the plugin dependency identifier in the docs

- src/main/groovy/com/github/jengelman/gradle/plugins/shadow/ShadowExtension.groovy
Sometimes the publication already has a pom, so adding a node will result in a duplicated dependencies block
> Do not add a dependencies block if it's already there

- src/main/groovy/com/github/jengelman/gradle/plugins/shadow/relocation/SimpleRelocator.groovy
fix #764.
If rawString is true, pattern and shadedPattern will be null, gradle will throw exception if not have `@Optional` annotation.
> Fix value not set when rawString is true.

- src/main/groovy/com/github/jengelman/gradle/plugins/shadow/transformers/Log4j2PluginsCacheFileTransformer.groovy
This transfomer doesn't take any custom inputs; it has
deterministic behaviour based on the files getting shaded.
This means it doesn't pose any additional requirements on the
cacheability of the overall ShadowJar task. Therefore we
should be able to mark it cacheable.
> Mark the Log4j2PluginsCacheFileTransformer as cacheable.

- src/main/groovy/com/github/jengelman/gradle/plugins/shadow/ShadowApplicationPlugin.groovy
- src/main/groovy/com/github/jengelman/gradle/plugins/shadow/ShadowJavaPlugin.groovy
See https://docs.gradle.org/current/userguide/upgrading_version_7.html#all_convention_deprecation that happened with Gradle 7.0.
Using conventions will start emitting deprecation warnings in Gradle 8.1.
> Prefer using plugin extensions over deprecated conventions

- src/main/groovy/com/github/jengelman/gradle/plugins/shadow/internal/CleanProperties.groovy
- src/main/groovy/com/github/jengelman/gradle/plugins/shadow/transformers/PropertiesFileTransformer.groovy
- src/test/groovy/com/github/jengelman/gradle/plugins/shadow/transformers/PropertiesFileTransformerTest.groovy
PropertiesFileTransformer uses `java.utils.Properties` internally as a storage.
`java.utils.Properties` `store0()` contains `bw.write("#" + new Date().toString());` that prepends current timestamp before any content (after comments).
This effectively breaks reproducible builds that use PropertiesFileTransformer because every new build has different timestamp in transformed files.
CleanProperties implementation is introduced in order to remove prepended timestamp when creating output stream.
> Introduce CleanProperties

- src/main/groovy/com/github/jengelman/gradle/plugins/shadow/impl/RelocatorRemapper.groovy
> Fix RelocatorRemapper: do not map inner class name if not changed

- src/docs/configuration/README.md
- src/main/groovy/com/github/jengelman/gradle/plugins/shadow/ShadowJavaPlugin.groovy
- src/main/groovy/com/github/jengelman/gradle/plugins/shadow/tasks/DefaultInheritManifest.groovy
- src/main/groovy/com/github/jengelman/gradle/plugins/shadow/tasks/InheritManifest.groovy
> Replace deprecated ConfigureUtil

- build.gradle
- buildSrc/build.gradle
- gradle/dependencies.gradle
- gradle/docs.gradle
- gradle/ghPages.gradle
- gradle/publish.gradle
- src/main/groovy/com/github/jengelman/gradle/plugins/shadow/ShadowExtension.groovy
- src/main/groovy/com/github/jengelman/gradle/plugins/shadow/ShadowJavaPlugin.groovy
- src/main/groovy/com/github/jengelman/gradle/plugins/shadow/internal/GradleVersionUtil.groovy
- src/main/groovy/com/github/jengelman/gradle/plugins/shadow/tasks/ShadowCopyAction.groovy
Follow up 1a57c16d8eacfc412e57370011272319844496bf.
> Polish outdated configs

- gradle/vuepress.gradle
The rule-generated `yarn_` tasks only get the dependency on the YarnInstallTask if they start with `yarn_run_`
So to make sure `yarn_build` works I've added the dependency manually
> Add missing dependency to `yarn_build`

- src/main/groovy/com/github/jengelman/gradle/plugins/shadow/tasks/ShadowCopyAction.groovy
- src/main/groovy/com/github/jengelman/gradle/plugins/shadow/transformers/ManifestAppenderTransformer.groovy
- src/main/groovy/com/github/jengelman/gradle/plugins/shadow/transformers/ManifestResourceTransformer.groovy
Follow up https://github.com/GradleUp/shadow/pull/876#discussion_r1698027680.
> Log ignored IO exceptions

- gradle.properties
- src/test/groovy/com/github/jengelman/gradle/plugins/shadow/ShadowPluginSpec.groovy
> Add `exclude gradleApi() by default` test

- README.md
- src/docs/README.md
See https://github.com/GradleUp/shadow/pull/928#issuecomment-2257050924
Existing users of the plugin might still remember the old owner and plugin ID, so this should hopefully reduce confusion and give further insight into the change.
Any feedback, especially regarding formatting or wording, is appreciated!
> Mention original owner and plugin ID

- build.gradle.kts
Now it's shadowed.
```
runtimeClasspath - Runtime classpath of source set 'main'.
+--- org.jdom:jdom2:2.0.6.1
+--- org.ow2.asm:asm:9.7
+--- org.ow2.asm:asm-commons:9.7
|    +--- org.ow2.asm:asm:9.7
|    \--- org.ow2.asm:asm-tree:9.7
|         \--- org.ow2.asm:asm:9.7
+--- commons-io:commons-io:2.16.1
+--- org.apache.ant:ant:1.10.15
|    \--- org.apache.ant:ant-launcher:1.10.15
+--- org.codehaus.plexus:plexus-utils:4.0.1
+--- org.codehaus.plexus:plexus-xml:4.0.4
|    \--- org.apache.maven:maven-xml-impl:4.0.0-alpha-9
|         +--- org.apache.maven:maven-api-xml:4.0.0-alpha-9
|         |    \--- org.apache.maven:maven-api-meta:4.0.0-alpha-9
|         \--- com.fasterxml.woodstox:woodstox-core:6.5.1
|              \--- org.codehaus.woodstox:stax2-api:4.2.1
+--- …
```
> Stop excluding ASM from jdependency

- src/docs/changes/README.md
- src/main/groovy/com/github/jengelman/gradle/plugins/shadow/ShadowPlugin.groovy
Configuring develocity build scan additional detail publishing breaks Gradle project isolation https://github.com/GradleUp/shadow/issues/907
This change adds a new property com.gradleup.shadow.enableDevelocityIntegration that defaults to true, however it allows folks to set it to false and make shadow plugin usage project isolation safe.
---
> Disable Develocity integration by default

- src/docs/.vuepress/config.js
Every doc page has a link labeld "Help improve these docs!" which produce 404s, e.g.: https://github.com/GradleUp/shadow/edit/master/src/docs/custom-tasks/README.md. 
According to [Vuepress docs](https://v1.vuepress.vuejs.org/theme/default-theme-config.html#git-repository-and-edit-links) one can change the branch via `docsBranch` property. I did not try if the change actually fixes the problem.
> Links from doc to source should point to main branch

- src/docs/custom-tasks/README.md
---
Adapts the docs at https://gradleup.com/shadow/custom-tasks/.
Using `testImplementation` does not work anymore with latest Gradle versions. It produces the following error:
```
Could not determine the dependencies of task ':testJar'.
> Resolving dependency configuration 'testImplementation' is not allowed as it is defined as 'canBeResolved=false'.
Instead, a resolvable ('canBeResolved=true') dependency configuration that extends 'testImplementation' should be resolved.
```
Instead, [Gradle docs](https://docs.gradle.org/current/userguide/java_plugin.html) hints that `testRuntimeClasspath` is a resolvable configuration.
> Fix documentation of custom tasks

- build-logic/src/main/kotlin/shadow.convention.publish.gradle.kts
- src/docs/changes/README.md
- src/main/groovy/com/github/jengelman/gradle/plugins/shadow/ShadowPlugin.groovy
fixes #964 using the solution suggested by @ljacomet at https://github.com/GradleUp/shadow/issues/964#issuecomment-2345532565
Tested to fix the issue (bring behavior back to how it was before 8.3.1/with the old plugin), and to give an error when both the current and old plugin are on the classpath.
Something else that came to mind regarding the legacy plugin is that if someone puts the new plugin on the classpath, but then applies the legacy plugin id, nothing will happen, which could be confusing. But resolving that is likely better addressed in a separate PR (if at all).
```
> Could not resolve all files for configuration ':build-logic:compileClasspath'.
> Could not resolve com.gradleup.shadow:shadow-gradle-plugin:8.3.3-SNAPSHOT.
Required by:
project :build-logic
> Module …
```
> Apply legacy plugin last, and declare capabilities for old plugins

- build.gradle.kts
- src/docs/changes/README.md
> Revert "Bump Java level to 11"

- src/docs/publishing/README.md
- Calling `from()` is necessary
- Update text to describe new API
- Add Kotlin DSL equivalent as comment
---
> Fix publishing docs after API change

- src/docs/changes/README.md
- src/main/groovy/com/github/jengelman/gradle/plugins/shadow/ShadowPlugin.groovy
> Remove Develocity integration

- src/docs/changes/README.md
- src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/transformers/Log4j2PluginsCacheFileTransformer.kt
- src/test/groovy/com/github/jengelman/gradle/plugins/shadow/transformers/Log4j2PluginsCacheFileTransformerSpec.groovy
Probably when an application is single module jar, there's no `Log4j2Plugins.dat` file in `META-INF`, that causes a warning `No Log4j plugin descriptor was found in the classpath.`.
I saw that `Log4j2PluginCacheFileTransformer.java` class was inspired by [this repo](https://github.com/apache/logging-log4j-transform) and there was a [fix](https://github.com/apache/logging-log4j-transform/commit/d4393b6be63c83697727b7f5b9c02e15381ae704) for a fat jar apps. Already tested locally and now it works.
Refs https://github.com/apache/logging-log4j-transform/pull/42.
---
> Fix single Log4j2Plugins.dat isn't included into fat jar

- src/docs/changes/README.md
- src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/transformers/ApacheLicenseResourceTransformer.kt
- src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/transformers/ApacheNoticeResourceTransformer.kt
- src/test/groovy/com/github/jengelman/gradle/plugins/shadow/transformers/ApacheLicenseResourceTransformerTest.groovy
- src/test/groovy/com/github/jengelman/gradle/plugins/shadow/transformers/ApacheNoticeResourceTransformerParameterTests.groovy
Refs https://github.com/apache/maven-shade-plugin/pull/51.
---
> Add .md support to the Apache License and Notice transformers

- api/shadow.api
- lint-baseline.xml
- src/docs/changes/README.md
- src/docs/configuration/relocation/README.md
- src/docs/plugins/README.md
- src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/ShadowJavaPlugin.kt
- src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/internal/AbstractDependencyFilter.kt
- src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/internal/DependencyFilter.kt
- src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/internal/UnusedTracker.kt
- src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/internal/Utils.kt
- src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/tasks/ShadowJar.kt
- src/test/groovy/com/github/jengelman/gradle/plugins/shadow/ConfigureShadowRelocationSpec.groovy
> Migrate `ShadowJar` to using lazy properties

- api/shadow.api
- src/docs/changes/README.md
- src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/internal/Utils.kt
- src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/tasks/ShadowJar.kt
- src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/transformers/ApacheNoticeResourceTransformer.kt
- src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/transformers/AppendingTransformer.kt
- src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/transformers/DontIncludeResourceTransformer.kt
- src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/transformers/IncludeResourceTransformer.kt
- src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/transformers/ManifestAppenderTransformer.kt
- src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/transformers/ManifestResourceTransformer.kt
- src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/transformers/PropertiesFileTransformer.kt
- src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/transformers/Transformer.kt
- src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/transformers/XmlAppendingTransformer.kt
- src/test/groovy/com/github/jengelman/gradle/plugins/shadow/TransformerSpec.groovy
- src/test/groovy/com/github/jengelman/gradle/plugins/shadow/transformers/ApacheNoticeResourceTransformerParameterTests.groovy
- src/test/groovy/com/github/jengelman/gradle/plugins/shadow/transformers/ApacheNoticeResourceTransformerTest.groovy
- src/test/groovy/com/github/jengelman/gradle/plugins/shadow/transformers/AppendingTransformerTest.groovy
- src/test/groovy/com/github/jengelman/gradle/plugins/shadow/transformers/ManifestAppenderTransformerTest.groovy
- src/test/groovy/com/github/jengelman/gradle/plugins/shadow/transformers/PropertiesFileTransformerSpec.groovy
- src/test/groovy/com/github/jengelman/gradle/plugins/shadow/transformers/PropertiesFileTransformerTest.groovy
- src/test/groovy/com/github/jengelman/gradle/plugins/shadow/transformers/TransformerSpecSupport.groovy
- src/test/groovy/com/github/jengelman/gradle/plugins/shadow/transformers/TransformerTestSupport.groovy
- src/test/groovy/com/github/jengelman/gradle/plugins/shadow/transformers/XmlAppendingTransformerTest.groovy
> Migrate transformers to using lazy properties

- api/shadow.api
- src/docs/changes/README.md
- src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/internal/Utils.kt
- src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/relocation/SimpleRelocator.kt
- src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/tasks/ShadowJar.kt
- src/test/groovy/com/github/jengelman/gradle/plugins/shadow/relocation/SimpleRelocatorParameterTest.groovy
- src/test/groovy/com/github/jengelman/gradle/plugins/shadow/relocation/SimpleRelocatorTest.groovy
- src/test/groovy/com/github/jengelman/gradle/plugins/shadow/transformers/Log4j2PluginsCacheFileTransformerSpec.groovy
> Migrate `SimpleRelocator` to using lazy properties

- api/shadow.api
- src/docs/changes/README.md
- src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/relocation/SimpleRelocator.kt
- src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/tasks/ShadowJar.kt
- src/test/groovy/com/github/jengelman/gradle/plugins/shadow/relocation/SimpleRelocatorParameterTest.groovy
- src/test/groovy/com/github/jengelman/gradle/plugins/shadow/relocation/SimpleRelocatorTest.groovy
- src/test/groovy/com/github/jengelman/gradle/plugins/shadow/transformers/Log4j2PluginsCacheFileTransformerSpec.groovy
- Reverts #1047.
- Keep the compatibility with https://github.com/GradleUp/shadow/blob/09be1065ab4ff475d15444046b00b2d86f9d83a2/src/main/groovy/com/github/jengelman/gradle/plugins/shadow/relocation/SimpleRelocator.groovy.
---
> Revert changes in SimpleRelocator

- src/docs/changes/README.md
> Fix PR reference number for removal of Develocity integration

- src/test/groovy/com/github/jengelman/gradle/plugins/shadow/transformers/ApacheLicenseResourceTransformerTest.groovy
- src/test/groovy/com/github/jengelman/gradle/plugins/shadow/transformers/ApacheNoticeResourceTransformerTest.groovy
- src/test/groovy/com/github/jengelman/gradle/plugins/shadow/transformers/AppendingTransformerTest.groovy
- src/test/groovy/com/github/jengelman/gradle/plugins/shadow/transformers/TransformerTestSupport.groovy
- src/test/groovy/com/github/jengelman/gradle/plugins/shadow/transformers/XmlAppendingTransformerTest.groovy
> Reuse Turkish locale setup

- src/test/.editorconfig
- src/test/groovy/com/github/jengelman/gradle/plugins/shadow/relocation/SimpleRelocatorParameterTest.groovy
- src/test/groovy/com/github/jengelman/gradle/plugins/shadow/relocation/SimpleRelocatorTest.groovy
- src/test/groovy/com/github/jengelman/gradle/plugins/shadow/transformers/ApacheLicenseResourceTransformerTest.groovy
- src/test/groovy/com/github/jengelman/gradle/plugins/shadow/transformers/ApacheNoticeResourceTransformerTest.groovy
- src/test/groovy/com/github/jengelman/gradle/plugins/shadow/transformers/AppendingTransformerTest.groovy
- src/test/groovy/com/github/jengelman/gradle/plugins/shadow/transformers/ComponentsXmlResourceTransformerTest.groovy
- src/test/groovy/com/github/jengelman/gradle/plugins/shadow/transformers/ManifestAppenderTransformerTest.groovy
- src/test/groovy/com/github/jengelman/gradle/plugins/shadow/transformers/PropertiesFileTransformerTest.groovy
- src/test/groovy/com/github/jengelman/gradle/plugins/shadow/transformers/TransformerTestSupport.groovy
- src/test/groovy/com/github/jengelman/gradle/plugins/shadow/transformers/XmlAppendingTransformerTest.groovy
> Reformat unit test sources for less diffs

- api/shadow.api
- src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/ShadowApplicationPlugin.kt
- src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/tasks/JavaJarExec.kt
Users can import the `runShadow` type in their build files.
Refs #1071.
> Move JavaJarExec out of internal

- build.gradle.kts
- src/funcTest/groovy/com/github/jengelman/gradle/plugins/shadow/transformers/PropertiesFileTransformerSpec.groovy
- src/funcTest/groovy/com/github/jengelman/gradle/plugins/shadow/transformers/TransformerSpecSupport.groovy
- src/test/kotlin/com/github/jengelman/gradle/plugins/shadow/transformers/ApacheNoticeResourceTransformerTest.kt
- src/test/kotlin/com/github/jengelman/gradle/plugins/shadow/transformers/AppendingTransformerTest.kt
- src/test/kotlin/com/github/jengelman/gradle/plugins/shadow/transformers/ManifestAppenderTransformerTest.kt
- src/test/kotlin/com/github/jengelman/gradle/plugins/shadow/transformers/PropertiesFileTransformerTest.kt
- src/test/kotlin/com/github/jengelman/gradle/plugins/shadow/transformers/XmlAppendingTransformerTest.kt
- src/test/kotlin/com/github/jengelman/gradle/plugins/shadow/util/Utils.kt
- Reverts #1081.
- Refs #1084.
> Revert "Add a new source set to share test kits (#1081)"

- api/shadow.api
- src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/tasks/ShadowJar.kt
- src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/transformers/Transformer.kt
- src/test/kotlin/com/github/jengelman/gradle/plugins/shadow/transformers/ApacheLicenseResourceTransformerTest.kt
- src/test/kotlin/com/github/jengelman/gradle/plugins/shadow/transformers/ApacheNoticeResourceTransformerTest.kt
- src/test/kotlin/com/github/jengelman/gradle/plugins/shadow/transformers/AppendingTransformerTest.kt
- src/test/kotlin/com/github/jengelman/gradle/plugins/shadow/transformers/ComponentsXmlResourceTransformerTest.kt
- src/test/kotlin/com/github/jengelman/gradle/plugins/shadow/transformers/ManifestAppenderTransformerTest.kt
- src/test/kotlin/com/github/jengelman/gradle/plugins/shadow/transformers/PropertiesFileTransformerTest.kt
- src/test/kotlin/com/github/jengelman/gradle/plugins/shadow/transformers/TransformerTestSupport.kt
- src/test/kotlin/com/github/jengelman/gradle/plugins/shadow/transformers/XmlAppendingTransformerTest.kt
> Add a factory function for creating `Transformer`s

- api/shadow.api
- src/docs/changes/README.md
- src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/relocation/SimpleRelocator.kt
- src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/tasks/ShadowJar.kt
- src/test/kotlin/com/github/jengelman/gradle/plugins/shadow/relocation/SimpleRelocatorTest.kt
- src/test/kotlin/com/github/jengelman/gradle/plugins/shadow/transformers/Log4j2PluginsCacheFileTransformerTest.kt
- src/test/kotlin/com/github/jengelman/gradle/plugins/shadow/util/Utils.kt
- Reworks #1047.
- Refs https://github.com/GradleUp/shadow/pull/524#discussion_r1865187155.
---
> Only expose `includes` and `excludes` as inputs in `SimpleRelocator`

- src/docs/changes/README.md
- src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/internal/UnusedTracker.kt
https://docs.gradle.org/8.12/userguide/upgrading_version_8.html#deprecate_self_resolving_dependency
---
> Replace deprecated `SelfResolvingDependency` with `FileCollectionDependency`

- src/funcTest/groovy/com/github/jengelman/gradle/plugins/shadow/BasePluginSpecification.groovy
- src/funcTest/groovy/com/github/jengelman/gradle/plugins/shadow/PublishingSpec.groovy
- src/funcTest/groovy/com/github/jengelman/gradle/plugins/shadow/ShadowPluginSpec.groovy
- src/funcTest/groovy/com/github/jengelman/gradle/plugins/shadow/TransformerSpec.groovy
- src/funcTest/groovy/com/github/jengelman/gradle/plugins/shadow/caching/AbstractCachingSpec.groovy
- src/funcTest/groovy/com/github/jengelman/gradle/plugins/shadow/caching/MinimizationCachingSpec.groovy
- src/funcTest/groovy/com/github/jengelman/gradle/plugins/shadow/caching/RelocationCachingSpec.groovy
- src/funcTest/groovy/com/github/jengelman/gradle/plugins/shadow/caching/ShadowJarCachingSpec.groovy
- src/funcTest/groovy/com/github/jengelman/gradle/plugins/shadow/caching/TransformCachingSpec.groovy
- src/intiTest/kotlin/com/github/jengelman/gradle/plugins/shadow/ApplicationTest.kt
- src/intiTest/kotlin/com/github/jengelman/gradle/plugins/shadow/BasePluginTest.kt
- src/intiTest/kotlin/com/github/jengelman/gradle/plugins/shadow/ConfigurationCacheSpec.kt
- src/intiTest/kotlin/com/github/jengelman/gradle/plugins/shadow/FilteringTest.kt
- src/intiTest/kotlin/com/github/jengelman/gradle/plugins/shadow/RelocationTest.kt
> Align logic for functional test kits

- src/intiTest/kotlin/com/github/jengelman/gradle/plugins/shadow/ApplicationTest.kt
- src/intiTest/kotlin/com/github/jengelman/gradle/plugins/shadow/BasePluginTest.kt
- src/intiTest/kotlin/com/github/jengelman/gradle/plugins/shadow/ConfigurationCacheSpec.kt
- src/intiTest/kotlin/com/github/jengelman/gradle/plugins/shadow/FilteringTest.kt
- src/intiTest/kotlin/com/github/jengelman/gradle/plugins/shadow/RelocationTest.kt
- src/intiTest/kotlin/com/github/jengelman/gradle/plugins/shadow/ShadowPluginTest.kt
- src/intiTest/kotlin/com/github/jengelman/gradle/plugins/shadow/transformers/BaseTransformerTest.kt
- src/intiTest/kotlin/com/github/jengelman/gradle/plugins/shadow/transformers/ServiceFileTransformerTest.kt
- src/intiTest/kotlin/com/github/jengelman/gradle/plugins/shadow/transformers/TransformersTest.kt
- src/intiTest/kotlin/com/github/jengelman/gradle/plugins/shadow/util/JarPath.kt
> Add `JarPath` to simplify assertions

- api/shadow.api
- src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/transformers/GroovyExtensionModuleTransformer.kt
> Public const values of `GroovyExtensionModuleTransformer`

- api/shadow.api
- src/intiTest/kotlin/com/github/jengelman/gradle/plugins/shadow/transformers/GroovyExtensionModuleTransformerTest.kt
- src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/transformers/GroovyExtensionModuleTransformer.kt
> Rename const values

- src/docs/plugins/README.md
> Tweak the doc about packaging Gradle plugins

- src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/tasks/ShadowCopyAction.kt
- Follow up #1028.
- Refs #1146.
> Keep the original `IOException` handling in `ShadowCopyAction.execute`

- .github/renovate.json5
- src/docs/changes/README.md
- src/functionalTest/kotlin/com/github/jengelman/gradle/plugins/shadow/ShadowPluginTest.kt
- src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/tasks/ShadowCopyAction.kt
- Closes #915.
- Closes #916.
---
> Fail builds if processing bad jars

- src/functionalTest/kotlin/com/github/jengelman/gradle/plugins/shadow/ShadowPluginTest.kt
> Check `Class-Path` in shadowed Gradle plugin jar

- src/docs/publishing/README.md
- src/functionalTest/kotlin/com/github/jengelman/gradle/plugins/shadow/PublishingTest.kt
> Show how to publish the shadowed jar only

- .github/workflows/ci.yml
- .github/workflows/release.yml
https://github.blog/changelog/2025-01-16-linux-arm64-hosted-runners-now-available-for-free-in-public-repositories-public-preview/
> Try out ubuntu-24.04-arm on CI

- src/docs/changes/README.md
- src/functionalTest/kotlin/com/github/jengelman/gradle/plugins/shadow/JavaPluginTest.kt
- src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/ShadowJavaPlugin.kt
> Exclude module-info.class in Multi-Release folders by default

- src/docs/configuration/merging/README.md
- Follow up #1175.
- Refs https://github.com/apache/logging-log4j-transform/issues/73#issuecomment-2609408107.
> Note using `Log4j2PluginsCacheFileTransformer` in doc

- src/docs/changes/README.md
- src/functionalTest/kotlin/com/github/jengelman/gradle/plugins/shadow/ApplicationPluginTest.kt
- src/functionalTest/kotlin/com/github/jengelman/gradle/plugins/shadow/BasePluginTest.kt
- src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/ShadowApplicationPlugin.kt
> Support overriding `mainClass` provided by `JavaApplication`

- src/functionalTest/kotlin/com/github/jengelman/gradle/plugins/shadow/ApplicationPluginTest.kt
- src/functionalTest/kotlin/com/github/jengelman/gradle/plugins/shadow/BasePluginTest.kt
- src/functionalTest/kotlin/com/github/jengelman/gradle/plugins/shadow/util/RunProcess.kt
> Test start scripts running

- src/docs/.vuepress/config.js
See `view-source:https://gradleup.com/shadow/`
Docs: https://v1.vuepress.vuejs.org/config/#title
---
> Move `title` configuration in `config.js` to fix default HTML title

- src/docs/changes/README.md
- src/functionalTest/kotlin/com/github/jengelman/gradle/plugins/shadow/PublishingTest.kt
- src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/ShadowJavaPlugin.kt
> Inject `TargetJvmVersion` attr for GMM

- api/shadow.api
- src/docs/changes/README.md
- src/functionalTest/kotlin/com/github/jengelman/gradle/plugins/shadow/caching/ShadowJarCachingTest.kt
- src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/tasks/ShadowJar.kt
> Fix `ShadowJar` not being successful after `includes` or `excludes` are changed

- src/functionalTest/kotlin/com/github/jengelman/gradle/plugins/shadow/transformers/TransformersTest.kt
- src/test/kotlin/com/github/jengelman/gradle/plugins/shadow/transformers/Log4j2PluginsCacheFileTransformerTest.kt
- src/test/kotlin/com/github/jengelman/gradle/plugins/shadow/transformers/PropertiesFileTransformerTest.kt
- src/test/kotlin/com/github/jengelman/gradle/plugins/shadow/transformers/ServiceFileTransformerTest.kt
> Refine parameterized unit tests

- src/functionalTest/kotlin/com/github/jengelman/gradle/plugins/shadow/BasePluginTest.kt
- src/functionalTest/kotlin/com/github/jengelman/gradle/plugins/shadow/FilteringTest.kt
- src/functionalTest/kotlin/com/github/jengelman/gradle/plugins/shadow/caching/ShadowJarCachingTest.kt
Follow up #1206.
I missed that we can use `MinimizeDependencyFilter` as the fallback for testing.
> Add a caching test for `ShadowJar.dependencyFilter`

- api/shadow.api
- src/docs/application-plugin/README.md
- src/docs/changes/README.md
- src/functionalTest/kotlin/com/github/jengelman/gradle/plugins/shadow/ApplicationPluginTest.kt
- src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/ShadowApplicationPlugin.kt
- Closes #118.
- Closes #133.
- Follow up #1216.
Syncs with https://github.com/gradle/gradle/blob/45a20d82b623786d19b50185e595adf3d7b196b2/platforms/jvm/plugins-application/src/main/java/org/gradle/api/plugins/ApplicationPlugin.java.
---
> Sync `ShadowApplicationPlugin` with `ApplicationPlugin`

- .github/workflows/ci.yml
- .github/workflows/release.yml
Failures like https://github.com/GradleUp/shadow/actions/runs/13173107496/job/36766857773 are too annoying!
Reverts GradleUp/shadow#1164.
> Revert "Try out ubuntu-24.04-arm on CI"

- src/docs/configuration/relocation/README.md
> Fix typo in relocation guide when showing the relocated package name

- src/docs/changes/README.md
- src/functionalTest/kotlin/com/github/jengelman/gradle/plugins/shadow/JavaPluginTest.kt
- src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/internal/Utils.kt
- src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/tasks/ShadowJar.kt
> Inject `Multi-Release` attr if any dependency contains it

- src/functionalTest/kotlin/com/github/jengelman/gradle/plugins/shadow/BasePluginTest.kt
- src/functionalTest/kotlin/com/github/jengelman/gradle/plugins/shadow/caching/ShadowJarCachingTest.kt
- src/functionalTest/kotlin/com/github/jengelman/gradle/plugins/shadow/transformers/AppendingTransformerTest.kt
- src/functionalTest/kotlin/com/github/jengelman/gradle/plugins/shadow/transformers/GroovyExtensionModuleTransformerTest.kt
- src/functionalTest/kotlin/com/github/jengelman/gradle/plugins/shadow/transformers/ServiceFileTransformerTest.kt
- src/functionalTest/kotlin/com/github/jengelman/gradle/plugins/shadow/transformers/TransformersTest.kt
- src/functionalTest/kotlin/com/github/jengelman/gradle/plugins/shadow/transformers/XmlAppendingTransformerTest.kt
Local dependency jars should be included by `implementation` instead of `from`, `from` should copy the input files into the output shadowed jar without any unzipping.
Refs #1233.
> Correct `AbstractCopyTask.from` usages in functional tests

- api/shadow.api
- src/docs/changes/README.md
- src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/internal/RealStreamAction.kt
- src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/tasks/ShadowCopyAction.kt
- src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/tasks/ShadowJar.kt
> Move tracking unused classes logic out of `ShadowCopyAction`

- src/docs/configuration/README.md
- src/functionalTest/kotlin/com/github/jengelman/gradle/plugins/shadow/JavaPluginTest.kt
> Correct`inheritFrom` usages in Kotlin DSL

- src/functionalTest/kotlin/com/github/jengelman/gradle/plugins/shadow/JavaPluginTest.kt
- src/functionalTest/kotlin/com/github/jengelman/gradle/plugins/shadow/util/JarPath.kt
`Jar.manifest.mainAttributes` should never be empty.
> Tweak manifest attr size checks

- api/shadow.api
- src/docs/changes/README.md
- src/functionalTest/kotlin/com/github/jengelman/gradle/plugins/shadow/RelocationTest.kt
- src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/relocation/SimpleRelocator.kt
- src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/tasks/ShadowCopyAction.kt
- src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/tasks/ShadowJar.kt
- src/test/kotlin/com/github/jengelman/gradle/plugins/shadow/relocation/SimpleRelocatorTest.kt
- src/test/kotlin/com/github/jengelman/gradle/plugins/shadow/transformers/Log4j2PluginsCacheFileTransformerTest.kt
- src/test/kotlin/com/github/jengelman/gradle/plugins/shadow/transformers/ServiceFileTransformerTest.kt
- src/test/kotlin/com/github/jengelman/gradle/plugins/shadow/util/Utils.kt
> Reduce duplicated `SimpleRelocator` to improve performance

- api/shadow.api
- src/docs/changes/README.md
- src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/internal/AbstractDependencyFilter.kt
- src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/tasks/DependencyFilter.kt
- src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/tasks/ShadowJar.kt
- src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/tasks/ShadowSpec.kt
It should be a public API.
---
> Move `DependencyFilter` into tasks package

- gradle/libs.versions.toml
- src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/tasks/ShadowCopyAction.kt
- src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/transformers/ApacheLicenseResourceTransformer.kt
- src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/transformers/ApacheNoticeResourceTransformer.kt
- src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/transformers/AppendingTransformer.kt
- src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/transformers/ComponentsXmlResourceTransformer.kt
- src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/transformers/DontIncludeResourceTransformer.kt
- src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/transformers/GroovyExtensionModuleTransformer.kt
- src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/transformers/Log4j2PluginsCacheFileTransformer.kt
- src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/transformers/ManifestAppenderTransformer.kt
- src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/transformers/ManifestResourceTransformer.kt
- src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/transformers/PropertiesFileTransformer.kt
- src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/transformers/XmlAppendingTransformer.kt
> Returns the path of this file, relative to the root of the containing file tree. Always uses '/' as the hierarchy
separator, regardless of platform file separator. Same as calling getRelativePath().getPathString().
Closes #1273.
> Shorten obtaining relative paths

- api/shadow.api
- build.gradle.kts
- gradle/libs.versions.toml
- src/docs/.vuepress/config.js
- src/docs/changes/README.md
- src/docs/kmp-plugin/README.md
- src/functionalTest/kotlin/com/github/jengelman/gradle/plugins/shadow/BasePluginTest.kt
- src/functionalTest/kotlin/com/github/jengelman/gradle/plugins/shadow/KmpPluginTest.kt
- src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/ShadowJavaPlugin.kt
- src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/ShadowKmpPlugin.kt
- src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/ShadowPlugin.kt
> Compat Kotlin Multiplatform plugin

- api/shadow.api
- src/docs/changes/README.md
- src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/transformers/Transformer.kt
> Remove `Named` from the parents of `Transformer`

- api/shadow.api
- src/functionalTest/kotlin/com/github/jengelman/gradle/plugins/shadow/caching/TransformerCachingTest.kt
- src/functionalTest/kotlin/com/github/jengelman/gradle/plugins/shadow/transformers/TransformersTest.kt
- src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/transformers/ApacheLicenseResourceTransformer.kt
- src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/transformers/DontIncludeResourceTransformer.kt
- src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/transformers/IncludeResourceTransformer.kt
- src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/transformers/Transformer.kt
We can get rid of an explicit public object.
> Move `NoOpTransformer` into the companion object of `Transformer`

- api/shadow.api
- src/docs/changes/README.md
- src/docs/configuration/merging/README.md
- src/functionalTest/kotlin/com/github/jengelman/gradle/plugins/shadow/BasePluginTest.kt
- src/functionalTest/kotlin/com/github/jengelman/gradle/plugins/shadow/caching/TransformerCachingTest.kt
- src/functionalTest/kotlin/com/github/jengelman/gradle/plugins/shadow/transformers/TransformersTest.kt
- src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/tasks/ShadowCopyAction.kt
- src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/tasks/ShadowJar.kt
- src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/tasks/ShadowSpec.kt
- src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/transformers/ApacheLicenseResourceTransformer.kt
- src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/transformers/ApacheNoticeResourceTransformer.kt
- src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/transformers/AppendingTransformer.kt
- src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/transformers/ComponentsXmlResourceTransformer.kt
- src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/transformers/DontIncludeResourceTransformer.kt
- src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/transformers/GroovyExtensionModuleTransformer.kt
- src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/transformers/IncludeResourceTransformer.kt
- src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/transformers/Log4j2PluginsCacheFileTransformer.kt
- src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/transformers/ManifestAppenderTransformer.kt
- src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/transformers/ManifestResourceTransformer.kt
- src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/transformers/PropertiesFileTransformer.kt
- src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/transformers/ResourceTransformer.kt
- src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/transformers/ServiceFileTransformer.kt
- src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/transformers/XmlAppendingTransformer.kt
- src/test/kotlin/com/github/jengelman/gradle/plugins/shadow/transformers/BaseTransformerTest.kt
Aims to better align with the name of [org.apache.maven.plugins.shade.resource.ResourceTransformer.java](https://github.com/apache/maven-shade-plugin/blob/master/src/main/java/org/apache/maven/plugins/shade/resource/ResourceTransformer.java) and to distinguish itself from [org.gradle.api.Transformer.java](https://docs.gradle.org/current/javadoc/org/gradle/api/Transformer.html).
---
> Rename `Transformer` to `ResourceTransformer`

- api/shadow.api
- docs/changes/README.md
- src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/internal/AbstractDependencyFilter.kt
- src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/internal/DefaultInheritManifest.kt
- src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/relocation/SimpleRelocator.kt
- src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/tasks/DependencyFilter.kt
- src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/tasks/InheritManifest.kt
- src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/transformers/ManifestAppenderTransformer.kt
- src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/transformers/ManifestResourceTransformer.kt
We don't call them as "builders".
Follow up #1307.
> Remove redundant types from function returns

- src/test/kotlin/com/github/jengelman/gradle/plugins/shadow/relocation/SimpleRelocatorTest.kt
> Test post-pattern case for relocatePath

- build.gradle.kts
- src/functionalTest/kotlin/com/github/jengelman/gradle/plugins/shadow/BasePluginTest.kt
- src/functionalTest/kotlin/com/github/jengelman/gradle/plugins/shadow/FilteringTest.kt
- src/functionalTest/kotlin/com/github/jengelman/gradle/plugins/shadow/JavaPluginTest.kt
- src/functionalTest/kotlin/com/github/jengelman/gradle/plugins/shadow/PublishingTest.kt
- src/functionalTest/kotlin/com/github/jengelman/gradle/plugins/shadow/RelocationTest.kt
- src/functionalTest/kotlin/com/github/jengelman/gradle/plugins/shadow/caching/FilteringCachingTest.kt
- src/functionalTest/kotlin/com/github/jengelman/gradle/plugins/shadow/caching/ShadowJarCachingTest.kt
- src/functionalTest/kotlin/com/github/jengelman/gradle/plugins/shadow/transformers/ServiceFileTransformerTest.kt
> Test using type-safe accessors in `ShadowJar.dependencies`

- docs/configuration/README.md
- docs/configuration/dependencies/README.md
- Follow up #1233.
- Follow up #1285.
- Refs #1284.
> Update the section about "Embedding Jar Files Inside Your Shadow Jar"

- api/shadow.api
- docs/changes/README.md
- src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/internal/AbstractDependencyFilter.kt
- src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/tasks/DependencyFilter.kt
They are merged to accept `Any`.
Follow up #1322.
---
> Merge dependency and project overloads in `DependencyFilter`

- docs/changes/README.md
- docs/kmp-plugin/README.md
- gradle/libs.versions.toml
- src/functionalTest/kotlin/com/github/jengelman/gradle/plugins/shadow/KmpPluginTest.kt
- src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/ShadowKmpPlugin.kt
- Follow up #1280.
- Refs #1333.
---
> Set `Main-Class` attr for KMP 2.1.0 or above

- docs/configuration/merging/README.md
> Document handing `DuplicatesStrategy`

- docs/configuration/merging/README.md
> Note the mixed usages of `ResourceTransformer` and `DuplicatesStrategy`

- docs/changes/README.md
- src/functionalTest/kotlin/com/github/jengelman/gradle/plugins/shadow/ApplicationPluginTest.kt
- src/functionalTest/kotlin/com/github/jengelman/gradle/plugins/shadow/BasePluginTest.kt
- src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/ShadowApplicationPlugin.kt
- Split `installShadowOutputs` from `integrationWithApplicationPluginAndJavaToolchains`.
- Tweak `canOverrideMainClassAttrInManifestBlock`.
---
> No need to make `runShadow` depend on `installShadowDist`

- api/shadow.api
- docs/changes/README.md
- docs/custom-tasks/README.md
- docs/publishing/README.md
- src/functionalTest/kotlin/com/github/jengelman/gradle/plugins/shadow/JavaPluginTest.kt
- src/functionalTest/kotlin/com/github/jengelman/gradle/plugins/shadow/PublishingTest.kt
- src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/ShadowBasePlugin.kt
- src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/ShadowJavaPlugin.kt
Aligns with `Jar`, `SourceJarTask`, and so on.
---
> Move the group of `ShadowJar` from shadow to build

- src/functionalTest/kotlin/com/github/jengelman/gradle/plugins/shadow/KotlinPluginsTest.kt
> Check excluding stdlib entries in `KotlinPluginsTest`

- build-logic/src/main/kotlin/shadow.convention.publish.gradle.kts
Run `diff -r shadow-before/ shadow-after > diff.txt`:
```diff
diff --color -r
shadow-before/com.gradleup.shadow.gradle.plugin/9.0.0-SNAPSHOT/maven-metadata-local.xml
shadow-after/com.gradleup.shadow.gradle.plugin/9.0.0-SNAPSHOT/maven-metadata-local.xml
6c6
<     <lastUpdated>20250327025833</lastUpdated>
---
>     <lastUpdated>20250327030008</lastUpdated>
14c14
<         <updated>20250327025833</updated>
---
>         <updated>20250327030008</updated>
19c19
<         <updated>20250327025833</updated>
---
>         <updated>20250327030008</updated>
diff --color -r shadow-before/com.gradleup.shadow.gradle.plugin/maven-metadata-local.xml shadow-after/com.gradleup.shadow.gradle.plugin/maven-metadata-local.xml
10c10
<     <lastUpdated>20250327025833</lastUpdated>
---
> …
```
> No need to silence the compatibility warnings

- src/functionalTest/kotlin/com/github/jengelman/gradle/plugins/shadow/RelocationTest.kt
> Test that string consts are relocated by default

- docs/changes/README.md
- docs/kotlin-plugins/README.md
- gradle/libs.versions.toml
- src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/ShadowKmpPlugin.kt
https://github.com/JetBrains/kotlin/releases/tag/v1.9.0
https://youtrack.jetbrains.com/issue/KT-58661
https://github.com/JetBrains/kotlin/commit/e0389a0a870766b3d595b93c24905b491d02fab9
Follow up #1337.
---
> Set `Main-Class` attr for KMP 1.9.0 or above

- build.gradle.kts
- gradle/libs.versions.toml
> Bump Kotlin to 2.2.0-Beta1 for Java 24 support

- api/shadow.api
- docs/changes/README.md
- src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/relocation/RelocationContext.kt
> Fallback `RelocateClassContext` and `RelocatePathContext` to data classes

- docs/changes/README.md
Address https://github.com/GradleUp/shadow/pull/1245#discussion_r2146077499.
---
> Note the removal of `TransformerContext.getEntryTimestamp`

- build.gradle.kts
- docs/changes/README.md
As `org.apache.tools.zip.ZipOutputStream` is exposed in the public APIs:
```api
public class com/github/jengelman/gradle/plugins/shadow/transformers/DontIncludeResourceTransformer : com/github/jengelman/gradle/plugins/shadow/transformers/ResourceTransformer {
public fun modifyOutputStream (Lorg/apache/tools/zip/ZipOutputStream;Z)V
...
}
```
View the scope changes:
```diff
diff --color=auto -r before/shadow-gradle-plugin-9.0.0-SNAPSHOT.module after/shadow-gradle-plugin-9.0.0-SNAPSHOT.module
27a28,36
>       "dependencies": [
>         {
>           "group": "org.apache.ant",
>           "module": "ant",
>           "version": {
>             "requires": "1.10.15"
>           }
>         }
>       ],
85,91d93
<           "group": "org.apache.ant",
<           "module": "ant",
< …
```
> Expose Ant as `compile` scope

- build.gradle.kts
See
* https://www.morling.dev/blog/bytebuffer-and-the-dreaded-nosuchmethoderror
* https://github.com/gradle/gradle/issues/34035
* https://github.com/Kotlin/api-guidelines/issues/44
---
> Pin Java release on 11

- src/functionalTest/kotlin/com/github/jengelman/gradle/plugins/shadow/transformers/PropertiesFileTransformerTest.kt
- src/functionalTest/kotlin/com/github/jengelman/gradle/plugins/shadow/transformers/TransformersTest.kt
- src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/internal/CleanProperties.kt
Refs
- #622
- #856
- #858
- https://github.com/Goooler/shadow/pull/102
> Add functional tests for `PropertiesFileTransformer`

- .github/workflows/build.yml
- README.md
- build.gradle.kts
- docs/README.md
- docs/changes/README.md
- src/documentTest/kotlin/com/github/jengelman/gradle/plugins/shadow/snippet/SnippetExecutable.kt
- src/functionalTest/kotlin/com/github/jengelman/gradle/plugins/shadow/BasePluginTest.kt
- src/functionalTest/kotlin/com/github/jengelman/gradle/plugins/shadow/JavaPluginTest.kt
- src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/ShadowBasePlugin.kt
- src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/internal/GradleCompat.kt
- src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/internal/UnusedTracker.kt
> Bump the min Gradle requirement to 8.11 and update test matrix

- build.gradle.kts
```
Failed
A failure occurred while executing com.android.build.gradle.internal.lint.AndroidLintTask$AndroidLintLauncherWorkAction
> There was a failure while executing work items
> A failure occurred while executing com.android.build.gradle.internal.lint.AndroidLintWorkAction
> java.lang.ExceptionInInitializerError (no error message)
...
Caused by: java.lang.RuntimeException: Could not find installation home path. Please make sure product-info.json is present in the installation directory.
at com.intellij.openapi.application.PathManager.getHomePath(PathManager.java:113)
at com.intellij.openapi.application.PathManager.getHomePath(PathManager.java:82)
at com.intellij.openapi.application.PathManager.getConfigPath(PathManager.java:368)
at …
```
> Disable lint tasks on Windows

- api/shadow.api
- docs/changes/README.md
- docs/configuration/relocation/README.md
- docs/getting-started/README.md
- docs/gradle-plugins/README.md
- src/functionalTest/kotlin/com/github/jengelman/gradle/plugins/shadow/JavaPluginTest.kt
- src/functionalTest/kotlin/com/github/jengelman/gradle/plugins/shadow/RelocationTest.kt
- src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/tasks/ShadowJar.kt
> Rename `enableRelocation` to `enableAutoRelocation` and CLI option cleanups

- api/shadow.api
- docs/configuration/merging/README.md
- src/functionalTest/kotlin/com/github/jengelman/gradle/plugins/shadow/caching/ShadowJarCachingTest.kt
- src/functionalTest/kotlin/com/github/jengelman/gradle/plugins/shadow/transformers/ServiceFileTransformerTest.kt
- src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/tasks/ShadowJar.kt
- src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/transformers/PreserveFirstFoundResourceTransformer.kt
> Add more docs and tests for `DuplicatesStrategy`

- src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/ShadowApplicationPlugin.kt
- src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/tasks/ShadowJar.kt
They are not `convention`ed or `set`ed yet, seems we can call `convention`.
https://github.com/gradle/gradle/blob/665a9df021dfbf107a84f176d801394c9ef3aacd/platforms/jvm/language-java/src/main/java/org/gradle/api/tasks/JavaExec.java#L129-L130
> Prefer calling `convention` in `ShadowApplicationPlugin`

- src/docs/changes/README.md
- src/main/groovy/com/github/jengelman/gradle/plugins/shadow/internal/DefaultZipCompressor.groovy
When not using STORED entries use a BufferedOutputStream to avoid lots of small writes to the file system.
Testing this with a 300mb jar build I see the total build time going from 40s to 30s.
Note that it is not possible to do this with STORED entries as the implementation requires a RandomAccessFile to update the CRC after write.
---
> Use `BufferedOutputStream` when writing the Zip file to improve performance

- src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/tasks/ShadowJar.kt
`ZipEntryCompression` is an enum, there are only `DEFLATED` and `STORED` in it.
> Remove extra type check for `ZipEntryCompression`

- docs/changes/README.md
> Add migration example and changelog tweaks

- docs/changes/README.md
- docs/configuration/merging/README.md
- src/functionalTest/kotlin/com/github/jengelman/gradle/plugins/shadow/JavaPluginsTest.kt
- src/functionalTest/kotlin/com/github/jengelman/gradle/plugins/shadow/transformers/BaseTransformerTest.kt
- src/functionalTest/kotlin/com/github/jengelman/gradle/plugins/shadow/transformers/ServiceFileTransformerTest.kt
- src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/tasks/ShadowJar.kt
> Default `duplicatesStrategy` back to `EXCLUDE`

- docs/changes/README.md
- src/functionalTest/kotlin/com/github/jengelman/gradle/plugins/shadow/JavaPluginsTest.kt
- src/functionalTest/kotlin/com/github/jengelman/gradle/plugins/shadow/MinimizeTest.kt
- src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/internal/MinimizeDependencyFilter.kt
- Closes #1610.
- Fixes https://github.com/GradleUp/shadow/pull/1021#discussion_r2262468388.
---
> Fix the regression of resolving circular dependencies in `MinimizeDependencyFilter`

- src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/transformers/ApacheNoticeResourceTransformer.kt
We don't need thread-safety for this function.
> Use `StringBuilder` for `ApacheNoticeResourceTransformer.transform`

- docs/changes/README.md
- src/functionalTest/kotlin/com/github/jengelman/gradle/plugins/shadow/transformers/TransformersTest.kt
- src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/transformers/ApacheNoticeResourceTransformer.kt
> Fix using `ApacheNoticeResourceTransformer` without `projectName`

- docs/changes/README.md
- src/functionalTest/kotlin/com/github/jengelman/gradle/plugins/shadow/transformers/TransformersTest.kt
- src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/transformers/ApacheNoticeResourceTransformer.kt
> Fix extra indents of `ApacheNoticeResourceTransformer` output

- docs/changes/README.md
- src/functionalTest/kotlin/com/github/jengelman/gradle/plugins/shadow/MinimizeTest.kt
- src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/internal/UnusedTracker.kt
> Fix resolving BOM dependencies when `minimize` is enabled

- .github/workflows/build.yml
Easier to capture more details about
```
* What went wrong:
Execution failed for task ':lintReportJvm'.
> A failure occurred while executing com.android.build.gradle.internal.lint.AndroidLintTask$AndroidLintLauncherWorkAction
> There was a failure while executing work items
> A failure occurred while executing com.android.build.gradle.internal.lint.AndroidLintWorkAction
```
on CI.
> Run build tasks with stacktrace on CI

- build.gradle.kts
This doesn’t seem to help much with speeding things up...
> Remove override of `maxParallelForks`

- src/main/groovy/com/github/jengelman/gradle/plugins/shadow/ShadowExtension.groovy
- src/main/groovy/com/github/jengelman/gradle/plugins/shadow/ShadowJavaPlugin.groovy
Add a extension property to regulate whether a new variant is added to the java component. I must admit I don't know exactly why the variant was added. The [commit message](https://github.com/johnrengelman/shadow/commit/5c572a68bebf712a99854685d6c2834d146f9924) was only about support for Gradle 5 -> 6. So this is just a proposal.
Closes #651
> Allow for opt-out of the java shadowRuntimeElements variant

- api/shadow.api
- docs/changes/README.md
- docs/publishing/README.md
- src/functionalTest/kotlin/com/github/jengelman/gradle/plugins/shadow/JavaPluginsTest.kt
- src/functionalTest/kotlin/com/github/jengelman/gradle/plugins/shadow/PublishingTest.kt
- src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/ShadowBasePlugin.kt
- src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/ShadowExtension.kt
- src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/ShadowJavaPlugin.kt
> Allow opting out of `TARGET_JVM_VERSION_ATTRIBUTE`

- docs/changes/README.md
- src/functionalTest/kotlin/com/github/jengelman/gradle/plugins/shadow/BasePluginTest.kt
- src/functionalTest/kotlin/com/github/jengelman/gradle/plugins/shadow/RelocationTest.kt
- src/functionalTest/kotlin/com/github/jengelman/gradle/plugins/shadow/util/JarPath.kt
- src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/internal/RelocatorRemapper.kt
- src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/tasks/ShadowCopyAction.kt
If we don't need to make any changes to the class, we should use the original bytes instead of letting ASM generate new ones. 
Some tools (e.g. https://plugins.gradle.org/plugin/com.palantir.baseline-class-uniqueness) use (hashes of) class file bytes to determine if there are classpath conflicts, and Shadow's current logic causes false positives.
But even in general, I believe it makes sense to change as little as we can.
A similar change was made to the maven shade plugin at https://github.com/apache/maven-shade-plugin/pull/95.
---
> Do not write modified class files for no-op relocations

- docs/configuration/merging/README.md
- src/functionalTest/kotlin/com/github/jengelman/gradle/plugins/shadow/transformers/ServiceFileTransformerTest.kt
- src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/tasks/ShadowJar.kt
> Document more about `eachFile`, `filesMatching`, and `filesNotMatching`

- docs/changes/README.md
- src/functionalTest/kotlin/com/github/jengelman/gradle/plugins/shadow/transformers/GroovyExtensionModuleTransformerTest.kt
- src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/transformers/GroovyExtensionModuleTransformer.kt
> Support relocating Groovy extensions in Module descriptors

- docs/changes/README.md
- src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/ShadowJavaPlugin.kt
> Note the breaking change caused by `afterEvaluate` usages

- docs/changes/README.md
- src/functionalTest/kotlin/com/github/jengelman/gradle/plugins/shadow/FilteringTest.kt
- src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/tasks/DependencyFilter.kt
> Fix excluding dependencies whose versions contain `+`

- api/shadow.api
- docs/changes/README.md
- docs/getting-started/README.md
- gradle/lint-baseline.xml
- src/functionalTest/kotlin/com/github/jengelman/gradle/plugins/shadow/ApplicationPluginTest.kt
- src/functionalTest/kotlin/com/github/jengelman/gradle/plugins/shadow/JavaPluginsTest.kt
- src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/ShadowApplicationPlugin.kt
- src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/ShadowKmpPlugin.kt
- src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/tasks/ShadowJar.kt
> Move injecting `Main-Class` manifest attr logic from `doFirst` into `copy`

- docs/changes/README.md
- src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/ShadowApplicationPlugin.kt
> TODO usages of `conventionMapping`

- api/shadow.api
- docs/application-plugin/README.md
- docs/changes/README.md
- src/functionalTest/kotlin/com/github/jengelman/gradle/plugins/shadow/JavaPluginsTest.kt
- src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/ShadowApplicationPlugin.kt
- src/test/kotlin/com/github/jengelman/gradle/plugins/shadow/ShadowPropertiesTest.kt
> Add task accessors and check more task properties

- docs/changes/README.md
- src/functionalTest/kotlin/com/github/jengelman/gradle/plugins/shadow/BasePluginTest.kt
- src/functionalTest/kotlin/com/github/jengelman/gradle/plugins/shadow/JavaPluginsTest.kt
- src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/tasks/ShadowJar.kt
> Fix the regression of registering `ShadowJar` tasks without `ShadowPlugin` applied
