GradleUp/shadow

README.md

Link from README to the Gradle Plugins page, for easier access.

link to Gradle Plugins page

---

src/main/groovy/com/github/jengelman/gradle/plugins/shadow/internal/DefaultZipCompressor.groovy
src/main/groovy/com/github/jengelman/gradle/plugins/shadow/internal/gradle111/Gradle111DefaultZipCompressor.groovy

Use BufferedOutputStream for zip archives

Use BufferedOutputStream

---

src/main/resources/com/github/jengelman/gradle/plugins/shadow/internal/windowsStartScript.txt

Quote the Jar path, in case it contains whitespace.

---

README.md

Fix the markdown in Latest Test Compatibility so GitHub generates a table.

Fix table markdown in README

---

src/docs/asciidoc/12-controlling-dependencies.adoc

This detail tripped me up and by looking at the issues, I am not the first one.
It would be nice if there were another work around.

Add doc section about embedding jars

---

gradle/dependencies.gradle

WIP: Update ASM to 6.1

---

src/main/groovy/com/github/jengelman/gradle/plugins/shadow/ShadowApplicationPlugin.groovy

Fix error "No value has been specified for property mainClassName"

---

src/main/groovy/com/github/jengelman/gradle/plugins/shadow/internal/UnusedTracker.groovy

Fixes https://github.com/johnrengelman/shadow/issues/425
and https://github.com/johnrengelman/shadow/issues/424

Support SelfResolvingDependency in shadowJars

---

build.gradle

https://blog.gradle.org/plugin-portal-update

Mandatory upgrade for plugin portal publshing

---

src/main/groovy/com/github/jengelman/gradle/plugins/shadow/tasks/ShadowCopyAction.groovy

One more time, @johnrengelman. I hope this solves once and for all the input stream issue that has plagued us over the years trying to stay current on Gradle. Please take a look - I'm not sure how you would approach testing this since it would require enough remapped classes to open sufficiently many files.
Note the culprit of our build failure this time is: https://github.com/johnrengelman/shadow/blob/master/src/main/groovy/com/github/jengelman/gradle/plugins/shadow/tasks/ShadowCopyAction.groovy#L331
My exception (not present with the fix):
```
[04:50:59][Step 1/3] org.gradle.api.GradleException: Could not add file '/home/teamcity/teamcity/work/728364bcea5b3a67/pipeline/platforms/db240/rdd/build/classes/scala/main/com/paxata/spark/ast/SampleByAST$$anonfun$76.class' to ZIP …
```

ensure input stream is closed when remapping classes

---

src/main/groovy/com/github/jengelman/gradle/plugins/shadow/PluginShadowPlugin.groovy
src/main/groovy/com/github/jengelman/gradle/plugins/shadow/ShadowApplicationPlugin.groovy
src/main/groovy/com/github/jengelman/gradle/plugins/shadow/ShadowBasePlugin.groovy
src/main/groovy/com/github/jengelman/gradle/plugins/shadow/ShadowExtension.groovy
src/main/groovy/com/github/jengelman/gradle/plugins/shadow/ShadowJavaPlugin.groovy

Have Shadow plugin take advantage of [task configuration avoidance](https://docs.gradle.org/current/userguide/task_configuration_avoidance.html) for its tasks.

Migrate to task configuration avoidance APIs

---

src/test/groovy/com/github/jengelman/gradle/plugins/shadow/ApplicationSpec.groovy
src/test/groovy/com/github/jengelman/gradle/plugins/shadow/ConfigurationCacheSpec.groovy
src/test/groovy/com/github/jengelman/gradle/plugins/shadow/ConfigureShadowRelocationSpec.groovy
src/test/groovy/com/github/jengelman/gradle/plugins/shadow/FilteringSpec.groovy
src/test/groovy/com/github/jengelman/gradle/plugins/shadow/PublishingSpec.groovy
src/test/groovy/com/github/jengelman/gradle/plugins/shadow/RelocationSpec.groovy
src/test/groovy/com/github/jengelman/gradle/plugins/shadow/ShadowPluginSpec.groovy
src/test/groovy/com/github/jengelman/gradle/plugins/shadow/TransformerSpec.groovy
src/test/groovy/com/github/jengelman/gradle/plugins/shadow/caching/AbstractCachingSpec.groovy
src/test/groovy/com/github/jengelman/gradle/plugins/shadow/caching/ShadowJarCachingSpec.groovy
src/test/groovy/com/github/jengelman/gradle/plugins/shadow/util/PluginSpecification.groovy

Currently, some tests are still failing. Fixing those requires merging #646  or #647.

Test for deprecations

---

gradle/dependencies.gradle

Fixes issues with records (closes #679)

chore: Update jdependency to 2.7.0

---

src/main/groovy/com/github/jengelman/gradle/plugins/shadow/transformers/ComponentsXmlResourceTransformer.groovy

This transformer with relocators currently fails because of signatures incompatibility

Fix relocation for ComponentsXmlResourceTransformer

---

src/main/groovy/com/github/jengelman/gradle/plugins/shadow/ShadowExtension.groovy

Fixes master after merging PR #769

Fix retrieval of dependencies node when publishing

---

gradle/dependencies.gradle

... to support upcoming release of JDK 20 (see https://asm.ow2.io/versions.html).

Upgrade dependency ASM from `9.3` to `9.4`

---

src/docs/configuration/dependencies/README.md

Remove extra colon in the docs.

remove extra colon

---

src/docs/configuration/relocation/README.md

Update relocation README after `ConfigureShadowRelocation` removal

---

src/docs/configuration/dependencies/README.md

The example as provided doesn't seem to work. Updating to what I believe is intended here.

Fix invalid example in docs

---

.github/workflows/ci.yml
.github/workflows/release.yml

This reverts 2a532a0310d87693f248504f83cb284947852b20.

Fix gh-pages deployment on CI

---

src/docs/configuration/README.md
src/docs/configuration/dependencies/README.md
src/docs/configuration/filtering/README.md
src/docs/configuration/merging/README.md
src/docs/configuration/minimizing/README.md
src/docs/configuration/relocation/README.md
src/docs/plugins/README.md
src/main/groovy/com/github/jengelman/gradle/plugins/shadow/transformers/PropertiesFileTransformer.groovy
src/test/groovy/com/github/jengelman/gradle/plugins/shadow/ConfigurationCacheSpec.groovy
src/test/groovy/com/github/jengelman/gradle/plugins/shadow/FilteringSpec.groovy
src/test/groovy/com/github/jengelman/gradle/plugins/shadow/PublishingSpec.groovy
src/test/groovy/com/github/jengelman/gradle/plugins/shadow/RelocationSpec.groovy
src/test/groovy/com/github/jengelman/gradle/plugins/shadow/ShadowPluginSpec.groovy
src/test/groovy/com/github/jengelman/gradle/plugins/shadow/TransformerSpec.groovy
src/test/groovy/com/github/jengelman/gradle/plugins/shadow/caching/MinimizationCachingSpec.groovy
src/test/groovy/com/github/jengelman/gradle/plugins/shadow/caching/RelocationCachingSpec.groovy
src/test/groovy/com/github/jengelman/gradle/plugins/shadow/caching/ShadowJarCachingSpec.groovy
src/test/groovy/com/github/jengelman/gradle/plugins/shadow/caching/TransformCachingSpec.groovy

Prefer lazy APIs over task accessing.
---

Recommend using Shadow task providers

---

build.gradle
src/docs/changes/README.md
src/main/groovy/com/github/jengelman/gradle/plugins/shadow/ShadowPlugin.groovy
src/main/groovy/com/github/jengelman/gradle/plugins/shadow/legacy/LegacyShadowPlugin.groovy
src/main/resources/META-INF/gradle-plugins/com.github.johnrengelman.shadow.properties
src/test/groovy/com/github/jengelman/gradle/plugins/shadow/ShadowPluginSpec.groovy

Apply legacy plugin

---

src/docs/changes/README.md
src/docs/publishing/README.md
src/main/groovy/com/github/jengelman/gradle/plugins/shadow/ShadowExtension.groovy
src/main/groovy/com/github/jengelman/gradle/plugins/shadow/ShadowJavaPlugin.groovy
src/test/groovy/com/github/jengelman/gradle/plugins/shadow/PublishingSpec.groovy
src/test/groovy/com/github/jengelman/gradle/plugins/shadow/util/PluginSpecification.groovy

Deprecate ShadowExtension.component

---

.editorconfig
api/build.gradle.kts
build.gradle.kts
settings.gradle.kts

Prepare Kotlin migration

---

api/shadow.api
lint-baseline.xml
src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/ShadowApplicationPlugin.kt
src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/ShadowJavaPlugin.kt
src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/ShadowPlugin.kt
src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/internal/UnusedTracker.kt
src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/relocation/SimpleRelocator.kt
src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/tasks/ShadowJar.kt
src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/transformers/ApacheNoticeResourceTransformer.kt
src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/transformers/Transformer.kt

Fix lint errors and cleanups

---

api/shadow.api
src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/relocation/SimpleRelocator.kt

Keep the binary compatibility with 8.x versions.

Overload SimpleRelocator

---

src/funcTest/groovy/com/github/jengelman/gradle/plugins/shadow/transformers/Log4j2PluginsCacheFileTransformerSpec.groovy
src/funcTest/groovy/com/github/jengelman/gradle/plugins/shadow/transformers/TransformerSpecSupport.groovy
src/test/groovy/com/github/jengelman/gradle/plugins/shadow/relocation/SimpleRelocatorTest.groovy
src/test/groovy/com/github/jengelman/gradle/plugins/shadow/transformers/ApacheNoticeResourceTransformerTest.groovy
src/test/groovy/com/github/jengelman/gradle/plugins/shadow/transformers/ComponentsXmlResourceTransformerTest.groovy
src/test/groovy/com/github/jengelman/gradle/plugins/shadow/transformers/ManifestAppenderTransformerTest.groovy
src/test/groovy/com/github/jengelman/gradle/plugins/shadow/transformers/PropertiesFileTransformerTest.groovy
src/test/groovy/com/github/jengelman/gradle/plugins/shadow/transformers/TransformerTestSupport.groovy

Simplify new instances in tests

---

api/shadow.api
src/docs/changes/README.md
src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/relocation/SimpleRelocator.kt

Follow up https://github.com/GradleUp/shadow/pull/1079#discussion_r1873458386.
---

Use `SetProperty` on `includes` and `excludes`

---

build-logic/build.gradle.kts

https://kotlinlang.org/docs/dokka-migration.html#multi-module-projects-without-convention-plugins

Migrate to Dokka's new coordinate

---

src/funcTest/groovy/com/github/jengelman/gradle/plugins/shadow/FilteringSpec.groovy
src/funcTest/groovy/com/github/jengelman/gradle/plugins/shadow/RelocationSpec.groovy
src/funcTest/groovy/com/github/jengelman/gradle/plugins/shadow/ShadowPluginSpec.groovy

Polish ignored functional tests

---

src/functionalTest/kotlin/com/github/jengelman/gradle/plugins/shadow/transformers/TransformersTest.kt
src/functionalTest/kotlin/com/github/jengelman/gradle/plugins/shadow/transformers/XmlAppendingTransformerTest.kt

Standalone `XmlAppendingTransformerTest`

---

src/functionalTest/kotlin/com/github/jengelman/gradle/plugins/shadow/ShadowPluginTest.kt

- Follow up #1117.
- Refs #1152.

Tweak disabled functional tests

---

src/functionalTest/kotlin/com/github/jengelman/gradle/plugins/shadow/PublishingTest.kt

- Follow up #1117.
- Refs #1150.

Clean up PublishingTest

---

src/functionalTest/kotlin/com/github/jengelman/gradle/plugins/shadow/BasePluginTest.kt
src/functionalTest/kotlin/com/github/jengelman/gradle/plugins/shadow/JavaPluginTest.kt

Check more cases for shadowed Gradle plugin

---

src/functionalTest/kotlin/com/github/jengelman/gradle/plugins/shadow/PublishingTest.kt

Groups
- #1154
- #1158
- d079e8b318e0603f78be71b09c05dcda07a2e85d

Tweak PublishingTest

---

build.gradle.kts

Add a new configuration for pluginClasspath in tests

---

api/shadow.api
src/docs/changes/README.md
src/docs/configuration/merging/README.md
src/functionalTest/kotlin/com/github/jengelman/gradle/plugins/shadow/transformers/AppendingTransformerTest.kt
src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/tasks/ShadowJar.kt
src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/tasks/ShadowSpec.kt
src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/transformers/AppendingTransformer.kt

- Closes #545.
- Closes #778.
- Closes #1168.
---

Support configuring `separator` in `AppendingTransformer`

---

src/functionalTest/kotlin/com/github/jengelman/gradle/plugins/shadow/transformers/AppendingTransformerTest.kt
src/functionalTest/kotlin/com/github/jengelman/gradle/plugins/shadow/transformers/GroovyExtensionModuleTransformerTest.kt
src/functionalTest/kotlin/com/github/jengelman/gradle/plugins/shadow/transformers/ServiceFileTransformerTest.kt

Merge duplicates using parameterized tests

---

src/functionalTest/kotlin/com/github/jengelman/gradle/plugins/shadow/ApplicationPluginTest.kt
src/functionalTest/kotlin/com/github/jengelman/gradle/plugins/shadow/BasePluginTest.kt

Say "Hello, World!"

---

src/docs/application-plugin/README.md
src/functionalTest/kotlin/com/github/jengelman/gradle/plugins/shadow/ApplicationPluginTest.kt

Show how to add extra files into distributions

---

src/docs/custom-tasks/README.md
src/functionalTest/kotlin/com/github/jengelman/gradle/plugins/shadow/BasePluginTest.kt
src/functionalTest/kotlin/com/github/jengelman/gradle/plugins/shadow/JavaPluginTest.kt

Declare manifest attributes in sample task

---

src/functionalTest/kotlin/com/github/jengelman/gradle/plugins/shadow/BasePluginTest.kt
src/functionalTest/kotlin/com/github/jengelman/gradle/plugins/shadow/JavaPluginTest.kt
src/functionalTest/kotlin/com/github/jengelman/gradle/plugins/shadow/PublishingTest.kt
src/functionalTest/kotlin/com/github/jengelman/gradle/plugins/shadow/util/GradleModuleMetadata.kt

Test publish jars that depend on shadow jars

---

.github/dependabot.yml
.github/workflows/ci.yml

For https://github.com/GradleUp/shadow/security/dependabot

Configure dependabot

---

src/docs/application-plugin/README.md
src/functionalTest/kotlin/com/github/jengelman/gradle/plugins/shadow/ApplicationPluginTest.kt

Verify `DEFAULT_JVM_OPTS` in start scripts

---

src/functionalTest/kotlin/com/github/jengelman/gradle/plugins/shadow/PublishingTest.kt

Remove some test function suffixes

---

api/shadow.api
src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/internal/AbstractDependencyFilter.kt
src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/internal/DependencyFilter.kt
src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/tasks/ShadowJar.kt
src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/transformers/ServiceFileTransformer.kt

Address comments and stuffs

---

src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/transformers/PropertiesFileTransformer.kt

Follow up https://github.com/GradleUp/shadow/pull/1036#discussion_r1930019332.

Avoid unnecessary for loops in `PropertiesFileTransformer`

---

api/shadow.api
src/functionalTest/kotlin/com/github/jengelman/gradle/plugins/shadow/FilteringTest.kt
src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/internal/AbstractDependencyFilter.kt
src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/internal/DependencyFilter.kt
src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/transformers/PropertiesFileTransformer.kt
src/test/kotlin/com/github/jengelman/gradle/plugins/shadow/transformers/PropertiesFileTransformerTest.kt

Get rid of `Closure` in public APIs

---

src/docs/changes/README.md
src/functionalTest/kotlin/com/github/jengelman/gradle/plugins/shadow/caching/TransformerCachingTest.kt
src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/transformers/ApacheLicenseResourceTransformer.kt
src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/transformers/ApacheNoticeResourceTransformer.kt
src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/transformers/ComponentsXmlResourceTransformer.kt
src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/transformers/DontIncludeResourceTransformer.kt
src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/transformers/IncludeResourceTransformer.kt
src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/transformers/ManifestAppenderTransformer.kt
src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/transformers/ManifestResourceTransformer.kt
src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/transformers/PropertiesFileTransformer.kt

Follow up 
- #524.
- #1036.
---

More cacheable `Transformer`s

---

src/functionalTest/kotlin/com/github/jengelman/gradle/plugins/shadow/caching/MinimizationCachingTest.kt
src/functionalTest/kotlin/com/github/jengelman/gradle/plugins/shadow/caching/RelocationCachingTest.kt
src/functionalTest/kotlin/com/github/jengelman/gradle/plugins/shadow/caching/ShadowJarCachingTest.kt

Shorten caching tests

---

api/shadow.api
src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/transformers/XmlAppendingTransformer.kt

Remove unused `XSI_NS` const value

---

src/functionalTest/kotlin/com/github/jengelman/gradle/plugins/shadow/ApplicationPluginTest.kt
src/functionalTest/kotlin/com/github/jengelman/gradle/plugins/shadow/BasePluginTest.kt
src/functionalTest/kotlin/com/github/jengelman/gradle/plugins/shadow/caching/BaseCachingTest.kt
src/functionalTest/kotlin/com/github/jengelman/gradle/plugins/shadow/caching/MinimizationCachingTest.kt
src/functionalTest/kotlin/com/github/jengelman/gradle/plugins/shadow/caching/RelocationCachingTest.kt
src/functionalTest/kotlin/com/github/jengelman/gradle/plugins/shadow/caching/ShadowJarCachingTest.kt
src/functionalTest/kotlin/com/github/jengelman/gradle/plugins/shadow/caching/TransformerCachingTest.kt

Tweak caching test base

---

src/functionalTest/kotlin/com/github/jengelman/gradle/plugins/shadow/caching/ApplicationCachingTest.kt

Add a caching test for `runShadow`

---

src/docs/changes/README.md
src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/ShadowApplicationPlugin.kt

Sync with https://github.com/gradle/gradle/blob/bcecbb416f19438c7532e309456e3c3ed287f8f5/platforms/jvm/plugins-application/src/main/java/org/gradle/api/plugins/ApplicationPlugin.java#L184-L203
---

Polish `startShadowScripts` registering

---

build.gradle.kts

Remove the workaround for Gradle issue 22765

---

api/shadow.api
src/docs/changes/README.md
src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/internal/RelocatorRemapper.kt
src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/tasks/ShadowCopyAction.kt

Mark `RelocatorRemapper` as `internal`

---

.github/renovate.json5
gradle/libs.versions.toml

Group ASM and jdependency updates

---

src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/transformers/ComponentsXmlResourceTransformer.kt

Write `ByteArray` directly

---

build.gradle.kts
src/docs/changes/README.md
src/functionalTest/kotlin/com/github/jengelman/gradle/plugins/shadow/transformers/TransformersTest.kt
src/test/kotlin/com/github/jengelman/gradle/plugins/shadow/transformers/Log4j2PluginsCacheFileTransformerTest.kt

Bump min Java requirement to 11

---

src/docs/changes/README.md
src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/transformers/Transformer.kt
src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/transformers/XmlAppendingTransformer.kt

Mark `Transformer` as throwing `IOException`

---

api/shadow.api
lint-baseline.xml
src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/internal/DefaultZipCompressor.kt
src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/internal/RealStreamAction.kt
src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/internal/ZipCompressor.kt
src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/tasks/ShadowCopyAction.kt

Update `ShadowCopyAction` related logic and kdoc from Gradle

---

api/shadow.api
lint-baseline.xml
src/docs/changes/README.md
src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/internal/RealStreamAction.kt
src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/tasks/ShadowCopyAction.kt

Remove `BaseStreamAction`

---

src/functionalTest/kotlin/com/github/jengelman/gradle/plugins/shadow/ApplicationPluginTest.kt
src/functionalTest/kotlin/com/github/jengelman/gradle/plugins/shadow/BasePluginTest.kt
src/functionalTest/kotlin/com/github/jengelman/gradle/plugins/shadow/FilteringTest.kt
src/functionalTest/kotlin/com/github/jengelman/gradle/plugins/shadow/JavaPluginTest.kt
src/functionalTest/kotlin/com/github/jengelman/gradle/plugins/shadow/PublishingTest.kt
src/functionalTest/kotlin/com/github/jengelman/gradle/plugins/shadow/RelocationTest.kt
src/functionalTest/kotlin/com/github/jengelman/gradle/plugins/shadow/caching/RelocationCachingTest.kt
src/functionalTest/kotlin/com/github/jengelman/gradle/plugins/shadow/caching/ShadowJarCachingTest.kt
src/functionalTest/kotlin/com/github/jengelman/gradle/plugins/shadow/caching/TransformerCachingTest.kt
src/functionalTest/kotlin/com/github/jengelman/gradle/plugins/shadow/transformers/ServiceFileTransformerTest.kt
src/functionalTest/kotlin/com/github/jengelman/gradle/plugins/shadow/transformers/TransformersTest.kt

Replace `shadow` names in functional tests

---

src/functionalTest/kotlin/com/github/jengelman/gradle/plugins/shadow/ApplicationPluginTest.kt
src/functionalTest/kotlin/com/github/jengelman/gradle/plugins/shadow/BasePluginTest.kt
src/functionalTest/kotlin/com/github/jengelman/gradle/plugins/shadow/FilteringTest.kt
src/functionalTest/kotlin/com/github/jengelman/gradle/plugins/shadow/JavaPluginTest.kt
src/functionalTest/kotlin/com/github/jengelman/gradle/plugins/shadow/MinimizeTest.kt
src/functionalTest/kotlin/com/github/jengelman/gradle/plugins/shadow/RelocationTest.kt
src/functionalTest/kotlin/com/github/jengelman/gradle/plugins/shadow/caching/MinimizationCachingTest.kt
src/functionalTest/kotlin/com/github/jengelman/gradle/plugins/shadow/caching/RelocationCachingTest.kt
src/functionalTest/kotlin/com/github/jengelman/gradle/plugins/shadow/caching/ShadowJarCachingTest.kt

Improve `RelocationTest` and junit entry checks

---

lint-baseline.xml
src/docs/changes/README.md
src/functionalTest/kotlin/com/github/jengelman/gradle/plugins/shadow/BasePluginTest.kt
src/functionalTest/kotlin/com/github/jengelman/gradle/plugins/shadow/RelocationTest.kt
src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/tasks/ShadowCopyAction.kt

Fix the last modified time of shadowed directories

---

src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/tasks/ShadowJar.kt
src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/transformers/ServiceFileTransformer.kt

Replace TODOs for issue 1202

---

src/docs/publishing/README.md
src/functionalTest/kotlin/com/github/jengelman/gradle/plugins/shadow/PublishingTest.kt

https://docs.gradle.org/current/userguide/publishing_maven.html#publishing_maven:publications
https://docs.gradle.org/current/userguide/publishing_customization.html#sec:publishing_custom_artifacts_to_maven
https://docs.gradle.org/current/dsl/org.gradle.api.publish.maven.MavenPublication.html#org.gradle.api.publish.maven.MavenPublication:artifact(java.lang.Object)
Closes #1252.

Show how to publish custom ShadowJar outputs

---

src/docs/configuration/README.md
src/functionalTest/kotlin/com/github/jengelman/gradle/plugins/shadow/JavaPluginTest.kt

Update the usage of `ShadowJar.from`

---

api/shadow.api
lint-baseline.xml
src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/tasks/ShadowCopyAction.kt
src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/tasks/ShadowJar.kt

Addresses
- #107 
- #125 
- #281 
- #548 
- https://stackoverflow.com/questions/72620810
- https://discuss.gradle.org/t/better-documentation-for-zip64-option/13675
- https://youtrack.jetbrains.com/issue/KTOR-6884
And so on...

Improve the error message for zip64 option

---

src/functionalTest/kotlin/com/github/jengelman/gradle/plugins/shadow/BasePluginTest.kt

https://docs.gradle.org/current/userguide/configuration_cache.html#config_cache:usage:parallel

Enable parallel flags in functional tests

---

src/functionalTest/kotlin/com/github/jengelman/gradle/plugins/shadow/JavaPluginTest.kt

Update `canAddExtraFilesIntoShadowJar` for issue 947

---

src/functionalTest/kotlin/com/github/jengelman/gradle/plugins/shadow/JavaPluginTest.kt

Add a test for issue 520

---

src/docs/getting-started/README.md

Refs https://github.com/GradleUp/shadow/issues/710#issuecomment-981558387.

Note the exclusion of module-info.class

---

.gemini/config.yaml

https://developers.google.com/gemini-code-assist/docs/customize-gemini-behavior-github

Configure gemini pref

---

api/shadow.api
lint-baseline.xml
src/docs/changes/README.md
src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/internal/DefaultInheritManifest.kt
src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/tasks/ShadowJar.kt

Mark `DefaultInheritManifest` as `internal`

---

src/docs/getting-started/README.md
src/docs/introduction/README.md
src/integrationTest/kotlin/com/github/jengelman/gradle/plugins/shadow/executor/GroovyBuildExecutor.kt
src/integrationTest/kotlin/com/github/jengelman/gradle/plugins/shadow/fixture/GroovyDslFixture.kt

Update doc code blocks and tests

---

api/shadow.api
docs/changes/README.md
lint-baseline.xml
src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/tasks/ShadowJar.kt
src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/tasks/ShadowSpec.kt

- Refs #1306.
- Fixes https://scans.gradle.com/s/72ycaeh5aizwq/tests/overview?outcome=FAILED.
---

Polish `ShadowSpec`

---

docs/getting-started/README.md

They were not honored by pymdownx.
Follow up #1302.

Fix sub unordered lists

---

.github/actions/deploy-site/action.yml
.github/workflows/deploy.yml
.github/workflows/release.yml

https://docs.github.com/en/actions/sharing-automations/creating-actions/creating-a-composite-action

Reuse deploy steps via composite action

---

src/functionalTest/kotlin/com/github/jengelman/gradle/plugins/shadow/RelocationTest.kt

Add a test for relocating all packages but certain one

---

src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/ShadowApplicationPlugin.kt

With `applicationExtension` in `ShadowApplicationPlugin`

---

docs/configuration/relocation/README.md
src/functionalTest/kotlin/com/github/jengelman/gradle/plugins/shadow/RelocationTest.kt

Document relocate only trick

---

docs/configuration/merging/README.md

Fix `ResourceTransformer` API links

---

.github/actions/deploy-site/action.yml
.github/workflows/deploy.yml
.github/workflows/release.yml

Refs https://github.com/squidfunk/mkdocs-material/blob/0e75aef9ea9028dc5a2dea34fb5da8afb14911ae/.github/workflows/documentation.yml#L92-L112

Deploy sites by official actions

---

docs/configuration/README.md
docs/configuration/dependencies/README.md
docs/configuration/merging/README.md
docs/custom-tasks/README.md

It works for both local and remote sites.

Use relative API links in docs

---

docs/configuration/dependencies/README.md
docs/custom-tasks/README.md
docs/publishing/README.md
src/functionalTest/kotlin/com/github/jengelman/gradle/plugins/shadow/JavaPluginTest.kt
src/functionalTest/kotlin/com/github/jengelman/gradle/plugins/shadow/PublishingTest.kt

Follow up https://github.com/GradleUp/shadow/pull/1306#discussion_r2009683131.

Update configurations assignments and fix typos

---

src/functionalTest/kotlin/com/github/jengelman/gradle/plugins/shadow/MinimizationTest.kt

Rename `MinimizeTest` to `MinimizationTest`

---

docs/changes/README.md
docs/getting-started/README.md
src/functionalTest/kotlin/com/github/jengelman/gradle/plugins/shadow/JavaPluginTest.kt
src/functionalTest/kotlin/com/github/jengelman/gradle/plugins/shadow/MinimizeTest.kt
src/functionalTest/kotlin/com/github/jengelman/gradle/plugins/shadow/RelocationTest.kt
src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/tasks/ShadowJar.kt

https://docs.gradle.org/current/userguide/custom_tasks.html#sec:declaring_and_using_command_line_options
---

Support command line options for `ShadowJar`

---

docs/getting-started/README.md

https://docs.gradle.org/current/userguide/custom_tasks.html#sec:listing_task_options

See more info by listing command line options

---

docs/kotlin-plugins/README.md

Document adding stdlib into `compileClasspath`

---

.github/workflows/check-links.yml
.github/workflows/ci.yml
docs/changes/README.md

https://github.com/UmbrellaDocs/action-linkspector

Check and fix links

---

src/functionalTest/kotlin/com/github/jengelman/gradle/plugins/shadow/KotlinPluginsTest.kt

Test `doNotCreateJvmTargetEagerly`

---

.github/workflows/release.yml

https://github.com/ffurrer2/extract-release-notes/releases/tag/v2.3.0

Back to ffurrer2/extract-release-notes@v2

---

docs/changes/README.md

https://keepachangelog.com/en/1.1.0/
Refs #1393.

Honor keep-a-changelog header formats

---

docs/configuration/README.md
docs/configuration/merging/README.md
docs/publishing/README.md
src/functionalTest/kotlin/com/github/jengelman/gradle/plugins/shadow/JavaPluginTest.kt
src/functionalTest/kotlin/com/github/jengelman/gradle/plugins/shadow/PublishingTest.kt

Document publishing with custom archive properties

---

gradle/libs.versions.toml
src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/ShadowKmpPlugin.kt
src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/ShadowPlugin.kt
src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/internal/KotlinCompat.kt

Copy-pasted from https://github.com/vanniktech/gradle-maven-publish-plugin/blob/main/plugin/src/main/kotlin/com/vanniktech/maven/publish/MavenPublishBasePlugin.kt#L17-L41.

Polish KGP version checker

---

docs/android-plugins/README.md
mkdocs.yml

https://developer.android.com/build/publish-library/fused-library
Closes #1188.

Document Android Fused Library plugin

---

build.gradle.kts

https://kotlinlang.org/docs/whatsnew-eap.html?utm_campaign=kotlin-releases&utm_content=2-2-0-RC2&utm_medium=social&utm_source=twitter#changes-to-default-method-generation-for-interface-functions

Use new `jvmDefault` flags

---

.github/workflows/comment.yml
.github/workflows/commenter.yml

https://github.com/apexskier/github-release-commenter

Set up release commenter

---

build.gradle.kts
gradle/libs.versions.toml

Workaround for https://github.com/vanniktech/gradle-maven-publish-plugin/issues/926.

Replace pluginPublish with java-gradle-plugin

---

build.gradle.kts
gradle/libs.versions.toml

https://kotlinlang.org/docs/whatsnew22.html#binary-compatibility-validation-included-in-kotlin-gradle-plugin

Migrate BCV to the Kotlin's builtin

---

.github/renovate.json5
build.gradle.kts
docs/changes/README.md
gradle/libs.versions.toml
src/functionalTest/kotlin/com/github/jengelman/gradle/plugins/shadow/AndroidPluginTest.kt
src/functionalTest/kotlin/com/github/jengelman/gradle/plugins/shadow/BasePluginTest.kt
src/functionalTest/kotlin/com/github/jengelman/gradle/plugins/shadow/JavaPluginTest.kt
src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/ShadowPlugin.kt
src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/tasks/ShadowJar.kt

Fail build when inputting AAR files or using Shadow with AGP

---

src/functionalTest/kotlin/com/github/jengelman/gradle/plugins/shadow/RelocationTest.kt

Test relocation for case-sensitive and case-insensitive classes

---

docs/publishing/README.md

Document adding extra dependencies into POM files

---

api/shadow.api
docs/changes/README.md
docs/configuration/merging/README.md
src/functionalTest/kotlin/com/github/jengelman/gradle/plugins/shadow/transformers/TransformersTest.kt
src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/tasks/ShadowJar.kt
src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/transformers/PreserveFirstFoundResourceTransformer.kt

Add `PreserveFirstFoundResourceTransformer`

---

api/shadow.api
build.gradle.kts
docs/changes/README.md
src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/tasks/InheritManifest.kt
src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/tasks/ShadowSpec.kt
src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/transformers/ResourceTransformer.kt

Remove JVM default compat stuff

---

docs/configuration/relocation/README.md
src/functionalTest/kotlin/com/github/jengelman/gradle/plugins/shadow/RelocationTest.kt

- Closes #330.
- Follow up #1325.

Document relocating all packages but certain ones

---

docs/kotlin-plugins/README.md
src/documentTest/kotlin/com/github/jengelman/gradle/plugins/shadow/snippet/GroovyBuildExecutable.kt
src/documentTest/kotlin/com/github/jengelman/gradle/plugins/shadow/snippet/KotlinBuildExecutable.kt
src/documentTest/kotlin/com/github/jengelman/gradle/plugins/shadow/snippet/SnippetExecutable.kt

Run all doc test tasks depend on `Jar` types

---

docs/custom-tasks/README.md
src/functionalTest/kotlin/com/github/jengelman/gradle/plugins/shadow/JavaPluginTest.kt

Document registering a dependency only shadow JAR

---

src/functionalTest/kotlin/com/github/jengelman/gradle/plugins/shadow/KotlinPluginsTest.kt
src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/ShadowKmpPlugin.kt

Don't register `ShadowJar` tasks for multiple KMP JVM targets

---

src/functionalTest/kotlin/com/github/jengelman/gradle/plugins/shadow/KotlinPluginsTest.kt
src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/ShadowJavaPlugin.kt
src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/ShadowKmpPlugin.kt
src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/internal/GradleCompat.kt
src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/tasks/ShadowJar.kt

Configure manifest attrs for KMP JVM target artifacts task

---

src/functionalTest/kotlin/com/github/jengelman/gradle/plugins/shadow/RelocationTest.kt

Update tests for issue 606

---

api/shadow.api
docs/changes/README.md
src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/ShadowBasePlugin.kt
src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/ShadowExtension.kt

Remove deprecated `ShadowExtension.component`

---

api/shadow.api
docs/changes/README.md
src/functionalTest/kotlin/com/github/jengelman/gradle/plugins/shadow/ApplicationPluginTest.kt
src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/ShadowApplicationPlugin.kt
src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/ShadowBasePlugin.kt
src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/ShadowJavaPlugin.kt

Links
- #1566
- Something missing?
---

Move const values

---

build.gradle.kts

https://docs.gradle.com/develocity/test-distribution/#test_retry

Enable `testRetry`

---

.github/workflows/build.yml
.github/workflows/deploy.yml
.github/workflows/links.yml
.github/workflows/release.yml
.github/workflows/update-start-scripts.yml

https://github.blog/changelog/2025-08-07-arm64-hosted-runners-for-public-repositories-are-now-generally-available/

Try out ubuntu-24.04-arm runners

---

.github/workflows/build.yml
src/functionalTest/kotlin/com/github/jengelman/gradle/plugins/shadow/ApplicationPluginTest.kt
src/functionalTest/kotlin/com/github/jengelman/gradle/plugins/shadow/PublishingTest.kt

- Follow up #1608.
- Refs https://github.com/gradle/gradle/issues/29807.

Try out windows-11-arm runners

---

docs/changes/README.md

Prepare changelog for 9.0.1 and polish the items of 9.0.0

---

docs/changes/README.md
docs/configuration/merging/README.md
src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/tasks/ShadowJar.kt

Note more about the default `DuplicatesStrategy`

---

src/functionalTest/kotlin/com/github/jengelman/gradle/plugins/shadow/BasePluginTest.kt
src/functionalTest/kotlin/com/github/jengelman/gradle/plugins/shadow/CachingTest.kt
src/functionalTest/kotlin/com/github/jengelman/gradle/plugins/shadow/FilteringTest.kt
src/functionalTest/kotlin/com/github/jengelman/gradle/plugins/shadow/JavaPluginsTest.kt
src/functionalTest/kotlin/com/github/jengelman/gradle/plugins/shadow/MinimizeTest.kt
src/functionalTest/kotlin/com/github/jengelman/gradle/plugins/shadow/util/AppendableMavenRepository.kt

Support publishing all modules at once

---

src/functionalTest/kotlin/com/github/jengelman/gradle/plugins/shadow/BasePluginTest.kt

Assert build info like "will fail with an error in Gradle"

---

.github/workflows/build.yml
src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/ShadowBasePlugin.kt

- https://jakewharton.com/fan-in-to-a-single-required-github-action/
- https://github.com/JakeWharton/mosaic/blob/d4cc955eaadba0d18fcad5749c14a699415a1ae9/.github/workflows/build.yaml#L243-L259

Make `build-status` depend on more jobs

---

src/functionalTest/kotlin/com/github/jengelman/gradle/plugins/shadow/PublishingTest.kt

- Reverts #1190.
- Refs #1662.

Polish `PublishingTest`

---

src/functionalTest/kotlin/com/github/jengelman/gradle/plugins/shadow/PublishingTest.kt
src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/ShadowJavaPlugin.kt

Add logging when `addShadowVariantIntoJavaComponent` is disabled

---

src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/tasks/ShadowCopyAction.kt

Prefer using `when` in `visitFile`

---

build.gradle.kts
gradle/libs.versions.toml

Code highlighting for https://github.com/GradleUp/shadow/blob/53203e1b307fc5555abe46512bfc7bbea93f06d5/src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/tasks/ShadowJar.kt#L76-L80

Apply kotlin-reflect explicitly

---

docs/configuration/minimizing/README.md
src/functionalTest/kotlin/com/github/jengelman/gradle/plugins/shadow/MinimizeTest.kt

Clarify the minimization behavior for projects

---

docs/configuration/README.md
src/functionalTest/kotlin/com/github/jengelman/gradle/plugins/shadow/JavaPluginsTest.kt
src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/tasks/InheritManifest.kt

Prefer using `from` over `inheritFrom`

---

gradle/lint-baseline.xml
src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/ShadowApplicationPlugin.kt

Suppress usages of `conventionMapping`

---

docs/changes/README.md
src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/tasks/ShadowJar.kt
src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/transformers/ApacheNoticeResourceTransformer.kt
src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/transformers/AppendingTransformer.kt
src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/transformers/DontIncludeResourceTransformer.kt
src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/transformers/ManifestResourceTransformer.kt
src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/transformers/XmlAppendingTransformer.kt

Require most optional properties non-null

---

build.gradle.kts

Remove `downloadStartScripts` task

---

api/shadow.api
src/functionalTest/kotlin/com/github/jengelman/gradle/plugins/shadow/JavaPluginsTest.kt
src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/tasks/ShadowJar.kt

Test deferred `assemble` task dependencies

---

src/functionalTest/kotlin/com/github/jengelman/gradle/plugins/shadow/JavaPluginsTest.kt
src/test/kotlin/com/github/jengelman/gradle/plugins/shadow/ShadowPropertiesTest.kt

Group property value tests into a new class

---

.github/workflows/ci.yml

Add Java 25 into test matrix

---

build.gradle.kts
src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/ShadowBasePlugin.kt

```diff
24a25
>         "org.gradle.plugin.api-version": "8.11",
41,45c42,46
<           "size": 217573,
<           "sha512": "f14b96cd6fb11af08ea5be550e6e70c43a13933e8d54805aff1703be4e7d9afb402028352b3ec0829ee711f360c1e52c9948a9e24230d14f733fab4885a90913",
<           "sha256": "681603e58c691e87522c20ec0a8bf4620123929de04b0873f4412d95696d9898",
<           "sha1": "7bdec4422bc1a7154dc298427c625aeda137ac09",
<           "md5": "e94b96defed218255158cbe8327f8872"
---
>           "size": 217348,
>           "sha512": "0aac1c2d823806cb5e3642befea61368cf23de94891b019d489141e5b894a4e50d7b6309bfde0efacd846b1a21d9a0e59ad755c92cdc17ba7b28cb4348751331",
>           "sha256": "f10e9084b6186cc09f45c04018f1f6666810f4a76a7c775ea5609c30c0d8b99f",
>           "sha1": …
```

Set min Gradle requirement via `GradlePluginApiVersion` attribute
